export const families = [
  {
    name: "brain",
    component: "Brain",
    label: "Brain",
    offLabel: "Thinking off",
    group: "Development",
    tags: ["thinking", "reasoning"],
  },
  {
    name: "pin",
    component: "Pin",
    label: "Pin",
    offLabel: "Unpin",
    group: "Objects",
    tags: ["pinned", "unpin"],
  },
  {
    name: "eye",
    component: "Eye",
    label: "Eye",
    offLabel: "Hidden",
    group: "Objects",
    tags: ["visibility", "hide"],
  },
  {
    name: "bell",
    component: "Bell",
    label: "Bell",
    offLabel: "Muted",
    group: "Objects",
    tags: ["notification", "mute"],
  },
  {
    name: "plug",
    component: "Plug",
    label: "Plug",
    offLabel: "Disconnected",
    group: "Devices",
    tags: ["connection", "disconnect"],
  },
  {
    name: "strikethrough",
    component: "Strikethrough",
    label: "Strikethrough",
    source: "letter-s",
    modifier: "strike",
    group: "Typography",
    tags: ["text", "formatting"],
  },
  {
    name: "plus",
    component: "Plus",
    label: "Plus",
    group: "Navigation",
    tags: ["add", "new"],
  },
  {
    name: "minus",
    component: "Minus",
    label: "Minus",
    group: "Navigation",
    tags: ["subtract"],
  },
  {
    name: "x",
    component: "X",
    label: "X",
    group: "Navigation",
    tags: ["close", "cancel"],
  },
  {
    name: "check",
    component: "Check",
    label: "Check",
    group: "Navigation",
    tags: ["confirm", "done"],
  },
  {
    name: "square",
    component: "Square",
    label: "Square",
    group: "Geometry",
    tags: ["stop"],
  },
  {
    name: "circle",
    component: "Circle",
    label: "Circle",
    group: "Geometry",
    tags: [],
  },
  {
    name: "rectangle-horizontal",
    component: "RectangleHorizontal",
    label: "Rectangle Horizontal",
    group: "Geometry",
    tags: [],
  },
  {
    name: "rectangle-vertical",
    component: "RectangleVertical",
    label: "Rectangle Vertical",
    group: "Geometry",
    tags: [],
  },
  {
    name: "circle-check",
    base: "circle",
    component: "CircleCheck",
    label: "Circle Check",
    group: "Status",
    tags: ["done", "success"],
  },
  {
    name: "circle-dot",
    base: "circle",
    component: "CircleDot",
    label: "Circle Dot",
    group: "Status",
    tags: ["selected", "radio"],
  },
  {
    name: "chevron-up",
    component: "ChevronUp",
    label: "Chevron Up",
    group: "Navigation",
    tags: [],
  },
  {
    name: "chevron-down",
    component: "ChevronDown",
    label: "Chevron Down",
    group: "Navigation",
    tags: [],
  },
  {
    name: "chevron-left",
    component: "ChevronLeft",
    label: "Chevron Left",
    group: "Navigation",
    tags: [],
  },
  {
    name: "chevron-right",
    component: "ChevronRight",
    label: "Chevron Right",
    group: "Navigation",
    tags: [],
  },
  {
    name: "arrow-left",
    component: "ArrowLeft",
    label: "Arrow Left",
    group: "Navigation",
    tags: [],
  },
  {
    name: "arrow-right",
    component: "ArrowRight",
    label: "Arrow Right",
    group: "Navigation",
    tags: [],
  },
  {
    name: "arrow-up",
    component: "ArrowUp",
    label: "Arrow Up",
    group: "Navigation",
    tags: [],
  },
  {
    name: "arrow-up-right",
    component: "ArrowUpRight",
    label: "Arrow Up Right",
    group: "Navigation",
    tags: ["open", "external"],
  },
  {
    name: "maximize",
    component: "Maximize",
    label: "Maximize",
    group: "Navigation",
    tags: [],
  },
  {
    name: "ellipsis",
    component: "Ellipsis",
    label: "Ellipsis",
    group: "Navigation",
    tags: ["more", "menu"],
  },
  {
    name: "menu",
    component: "Menu",
    label: "Menu",
    group: "Navigation",
    tags: ["hamburger"],
  },
  {
    name: "activity",
    component: "Activity",
    label: "Activity",
    group: "Status",
    tags: ["pulse", "heartbeat"],
  },
  {
    name: "play",
    component: "Play",
    label: "Play",
    group: "Media",
    tags: [],
  },
  {
    name: "pause",
    component: "Pause",
    label: "Pause",
    group: "Media",
    tags: [],
  },
  {
    name: "skip-back",
    component: "SkipBack",
    label: "Skip Back",
    group: "Media",
    tags: [],
  },
  {
    name: "fold",
    component: "Fold",
    label: "Fold",
    group: "Navigation",
    tags: ["collapse", "vertical"],
  },
  {
    name: "unfold-vertical",
    component: "UnfoldVertical",
    label: "Unfold Vertical",
    group: "Navigation",
    tags: ["expand", "vertical"],
  },
  {
    name: "unfold-horizontal",
    component: "UnfoldHorizontal",
    label: "Unfold Horizontal",
    group: "Navigation",
    tags: ["expand", "horizontal"],
  },
  {
    name: "refresh",
    component: "Refresh",
    label: "Refresh",
    group: "Navigation",
    tags: ["loop", "sync"],
  },
  {
    name: "history",
    component: "History",
    label: "History",
    group: "Navigation",
    tags: ["undo", "recent"],
  },
  {
    name: "clock",
    base: "circle",
    component: "Clock",
    label: "Clock",
    group: "Status",
    tags: ["time", "wait"],
  },
  {
    name: "download",
    component: "Download",
    label: "Download",
    group: "Navigation",
    tags: [],
  },
  {
    name: "upload",
    component: "Upload",
    label: "Upload",
    group: "Navigation",
    tags: [],
  },
  {
    name: "search",
    component: "Search",
    label: "Search",
    group: "Navigation",
    tags: [],
  },
  {
    name: "zoom-in",
    component: "ZoomIn",
    label: "Zoom In",
    group: "Navigation",
    tags: [],
  },
  {
    name: "zoom-out",
    component: "ZoomOut",
    label: "Zoom Out",
    group: "Navigation",
    tags: [],
  },
  {
    name: "file",
    component: "File",
    label: "File",
    group: "Files",
    tags: [],
  },
  {
    name: "file-text",
    component: "FileText",
    label: "File Text",
    group: "Files",
    tags: ["document"],
    base: "file",
  },
  {
    name: "folder",
    component: "Folder",
    label: "Folder",
    group: "Files",
    tags: ["directory"],
  },
  {
    name: "folder-open",
    component: "FolderOpen",
    label: "Folder Open",
    group: "Files",
    tags: ["directory"],
  },
  {
    name: "folder-search",
    component: "FolderSearch",
    label: "Folder Search",
    base: "folder",
    group: "Files",
    tags: ["directory", "find"],
  },
  {
    name: "folder-plus",
    component: "FolderPlus",
    label: "Folder Plus",
    group: "Files",
    tags: ["directory", "add"],
    base: "folder",
  },
  {
    name: "folder-code",
    component: "FolderCode",
    label: "Folder Code",
    group: "Files",
    tags: [],
    base: "folder",
  },
  {
    name: "copy",
    component: "Copy",
    label: "Copy",
    group: "Files",
    tags: ["duplicate"],
  },
  {
    name: "close-others",
    component: "CloseOthers",
    label: "Close Others",
    group: "Files",
    tags: ["tabs"],
  },
  {
    name: "close-all",
    component: "CloseAll",
    label: "Close All",
    group: "Files",
    tags: ["tabs"],
  },
  {
    name: "archive",
    component: "Archive",
    label: "Archive",
    group: "Files",
    tags: [],
  },
  {
    name: "book",
    component: "Book",
    label: "Book",
    group: "Files",
    tags: [],
  },
  {
    name: "book-open",
    component: "BookOpen",
    label: "Book Open",
    group: "Files",
    tags: ["reading"],
  },
  {
    name: "library",
    component: "Library",
    label: "Library",
    group: "Files",
    tags: ["books"],
  },
  {
    name: "scroll-text",
    component: "ScrollText",
    label: "Scroll Text",
    group: "Files",
    tags: ["instructions", "log"],
  },
  {
    name: "clipboard-check",
    component: "ClipboardCheck",
    label: "Clipboard Check",
    group: "Files",
    tags: ["task", "done"],
    base: "clipboard",
  },
  {
    name: "calendar-plus",
    component: "CalendarPlus",
    label: "Calendar Plus",
    group: "Files",
    tags: ["schedule", "add"],
    base: "calendar",
  },
  {
    name: "calendar-x",
    component: "CalendarX",
    label: "Calendar X",
    group: "Files",
    tags: ["schedule", "remove"],
    base: "calendar",
  },
  {
    name: "calendar",
    component: "Calendar",
    label: "Calendar",
    group: "Files",
    tags: [],
    offLabel: "Calendar off",
  },
  {
    name: "panel-left",
    component: "PanelLeft",
    label: "Panel Left",
    group: "Layout",
    tags: [],
  },
  {
    name: "panel-right",
    component: "PanelRight",
    label: "Panel Right",
    group: "Layout",
    tags: [],
  },
  {
    name: "columns",
    component: "Columns",
    label: "Columns",
    group: "Layout",
    tags: [],
  },
  {
    name: "list",
    component: "List",
    label: "List",
    group: "Layout",
    tags: [],
  },
  {
    name: "list-checks",
    component: "ListChecks",
    label: "List Checks",
    group: "Layout",
    tags: ["tasks"],
  },
  {
    name: "chart-column",
    component: "ChartColumn",
    label: "Chart Column",
    group: "Layout",
    tags: ["statistics", "bars"],
  },
  {
    name: "blocks",
    component: "Blocks",
    label: "Blocks",
    group: "Layout",
    tags: ["grid", "extensions"],
  },
  {
    name: "diff",
    component: "Diff",
    label: "Diff",
    group: "Layout",
    tags: ["changes"],
  },
  {
    name: "wrap-text",
    component: "WrapText",
    label: "Wrap Text",
    group: "Layout",
    tags: ["line", "text"],
  },
  {
    name: "replace",
    component: "Replace",
    label: "Replace",
    group: "Layout",
    tags: ["swap"],
  },
  {
    name: "text-search",
    component: "TextSearch",
    label: "Text Search",
    group: "Layout",
    tags: ["find"],
  },
  {
    name: "settings",
    component: "Settings",
    label: "Settings",
    group: "Objects",
    tags: ["preferences", "gear"],
  },
  {
    name: "sun",
    component: "Sun",
    label: "Sun",
    group: "Nature",
    tags: ["light", "theme"],
  },
  {
    name: "moon",
    component: "Moon",
    label: "Moon",
    group: "Nature",
    tags: ["dark", "theme"],
  },
  {
    name: "sparkle",
    component: "Sparkle",
    label: "Sparkle",
    group: "Objects",
    tags: ["magic"],
  },
  {
    name: "sparkles",
    component: "Sparkles",
    label: "Sparkles",
    group: "Objects",
    tags: ["ai", "create"],
  },
  {
    name: "star",
    component: "Star",
    label: "Star",
    group: "Objects",
    tags: ["favorite"],
  },
  {
    name: "lightning",
    component: "Lightning",
    label: "Lightning",
    group: "Objects",
    tags: ["fast", "energy"],
  },
  {
    name: "gauge",
    component: "Gauge",
    label: "Gauge",
    group: "Status",
    tags: ["speed", "effort"],
  },
  {
    name: "target",
    base: "circle",
    component: "Target",
    label: "Target",
    group: "Status",
    tags: ["goal"],
  },
  {
    name: "crosshair",
    component: "Crosshair",
    label: "Crosshair",
    group: "Status",
    tags: ["focus"],
  },
  {
    name: "question",
    component: "Question",
    label: "Question",
    group: "Status",
    tags: ["help"],
  },
  {
    name: "alert",
    component: "Alert",
    label: "Alert",
    group: "Status",
    tags: ["warning"],
  },
  {
    name: "shield-check",
    component: "ShieldCheck",
    label: "Shield Check",
    group: "Security",
    tags: ["approval", "secure"],
    base: "shield",
  },
  {
    name: "user",
    component: "User",
    label: "User",
    group: "People",
    tags: ["person"],
    offLabel: "User off",
  },
  {
    name: "users",
    component: "Users",
    label: "Users",
    group: "People",
    tags: ["team"],
    offLabel: "Users off",
  },
  {
    name: "thumbs-up",
    component: "ThumbsUp",
    label: "Thumbs Up",
    group: "People",
    tags: ["like"],
  },
  {
    name: "thumbs-down",
    component: "ThumbsDown",
    label: "Thumbs Down",
    group: "People",
    tags: ["dislike"],
  },
  {
    name: "message",
    component: "Message",
    label: "Message",
    group: "Communication",
    tags: ["chat", "conversation"],
    offLabel: "Message off",
  },
  {
    name: "bot",
    component: "Bot",
    label: "Bot",
    group: "Development",
    tags: ["assistant", "agent"],
  },
  {
    name: "bug",
    component: "Bug",
    label: "Bug",
    group: "Development",
    tags: ["debug"],
  },
  {
    name: "trash",
    component: "Trash",
    label: "Trash",
    group: "Objects",
    tags: ["delete"],
  },
  {
    name: "pencil",
    component: "Pencil",
    label: "Pencil",
    group: "Objects",
    tags: ["edit"],
  },
  {
    name: "compose",
    component: "Compose",
    label: "Compose",
    group: "Objects",
    tags: ["new", "write"],
  },
  {
    name: "wrench",
    component: "Wrench",
    label: "Wrench",
    group: "Objects",
    tags: ["tool"],
  },
  {
    name: "image",
    component: "Image",
    label: "Image",
    group: "Media",
    tags: ["picture"],
    offLabel: "Image off",
  },
  {
    name: "map",
    component: "Map",
    label: "Map",
    group: "Navigation",
    tags: [],
  },
  {
    name: "flag",
    component: "Flag",
    label: "Flag",
    group: "Objects",
    tags: ["mark"],
  },
  {
    name: "package-search",
    component: "PackageSearch",
    label: "Package Search",
    group: "Files",
    tags: ["inspect"],
  },
  {
    name: "code",
    component: "Code",
    label: "Code",
    group: "Development",
    tags: ["brackets", "source"],
    offLabel: "Code off",
  },
  {
    name: "terminal",
    component: "Terminal",
    label: "Terminal",
    group: "Development",
    tags: ["shell", "console"],
    offLabel: "Terminal off",
  },
  {
    name: "send",
    component: "Send",
    label: "Send",
    group: "Communication",
    tags: ["paper", "plane", "submit"],
  },
  {
    name: "share",
    component: "Share",
    label: "Share",
    group: "Navigation",
    tags: [],
  },
  {
    name: "git-branch",
    component: "GitBranch",
    label: "Git Branch",
    group: "Development",
    tags: ["branch", "version"],
  },
  {
    name: "git-merge",
    component: "GitMerge",
    label: "Git Merge",
    group: "Development",
    tags: ["merge", "version"],
  },
  {
    name: "command",
    component: "Command",
    label: "Command",
    group: "Development",
    tags: ["keyboard", "shortcut"],
  },
  {
    name: "paperclip",
    component: "Paperclip",
    label: "Paperclip",
    group: "Objects",
    tags: ["attachment"],
  },
  {
    name: "webhook",
    component: "Webhook",
    label: "Webhook",
    group: "Development",
    tags: ["event", "hook"],
  },
  {
    name: "globe",
    base: "circle",
    component: "Globe",
    label: "Globe",
    group: "Objects",
    tags: ["web", "world"],
  },
  {
    name: "at",
    component: "At",
    label: "At",
    group: "Communication",
    tags: ["mention", "email"],
  },
  {
    name: "flame",
    component: "Flame",
    label: "Flame",
    group: "Objects",
    tags: ["fire"],
  },
  {
    name: "braces",
    component: "Braces",
    label: "Braces",
    group: "Development",
    tags: ["curly", "brackets"],
  },
  {
    name: "asterisk",
    component: "Asterisk",
    label: "Asterisk",
    group: "Typography",
    tags: ["required", "wildcard"],
  },
  {
    name: "cube-transparent",
    component: "CubeTransparent",
    label: "Cube Transparent",
    group: "Geometry",
    tags: ["wireframe", "3d"],
  },
  {
    name: "package",
    component: "Package",
    label: "Package",
    group: "Objects",
    tags: ["box", "parcel"],
  },
  {
    name: "pointer",
    component: "Pointer",
    label: "Pointer",
    group: "Navigation",
    tags: ["cursor", "click"],
  },
  {
    name: "flask",
    component: "Flask",
    label: "Flask",
    group: "Development",
    tags: ["experiment", "lab"],
  },
  {
    name: "flask-disabled",
    component: "FlaskDisabled",
    label: "Flask Disabled",
    group: "Development",
    tags: ["experiment", "disabled"],
  },
  {
    name: "radio-tower",
    component: "RadioTower",
    label: "Radio Tower",
    group: "Devices",
    tags: ["broadcast", "signal"],
  },
  {
    name: "microphone",
    component: "Microphone",
    label: "Microphone",
    group: "Media",
    tags: ["talk", "record"],
    offLabel: "Microphone off",
  },
  {
    name: "alarm-clock",
    component: "AlarmClock",
    label: "Alarm Clock",
    group: "Objects",
    tags: ["reminder"],
    offLabel: "Alarm Clock off",
  },
  {
    name: "atom",
    component: "Atom",
    label: "Atom",
    group: "Development",
    tags: ["science"],
  },
  {
    name: "database",
    component: "Database",
    label: "Database",
    group: "Development",
    tags: ["store"],
  },
  {
    name: "save",
    component: "Save",
    label: "Save",
    group: "Files",
    tags: ["disk"],
  },
  {
    name: "armchair",
    component: "Armchair",
    label: "Armchair",
    group: "Objects",
    tags: ["seat"],
  },
  {
    name: "headphones",
    component: "Headphones",
    label: "Headphones",
    group: "Media",
    tags: ["listen"],
    offLabel: "Headphones off",
  },
  {
    name: "lightbulb",
    component: "Lightbulb",
    label: "Lightbulb",
    group: "Objects",
    tags: ["idea"],
    offLabel: "Lightbulb off",
  },
  {
    name: "square-circle",
    component: "SquareCircle",
    label: "Square Circle",
    group: "Geometry",
    tags: ["overlap", "shapes"],
  },
  {
    name: "swatches",
    component: "Swatches",
    label: "Swatches",
    group: "Objects",
    tags: ["color", "palette"],
  },
  {
    name: "bookmark",
    component: "Bookmark",
    label: "Bookmark",
    group: "Objects",
    tags: [],
  },
  {
    name: "map-pin",
    component: "MapPin",
    label: "Map Pin",
    group: "Navigation",
    tags: ["location"],
  },
  {
    name: "bold",
    component: "Bold",
    label: "Bold",
    group: "Typography",
    tags: [],
  },
  {
    name: "hourglass",
    component: "Hourglass",
    label: "Hourglass",
    group: "Objects",
    tags: ["wait"],
  },
  {
    name: "video",
    component: "Video",
    label: "Video",
    group: "Media",
    tags: ["record"],
    offLabel: "Video off",
  },
  {
    name: "key",
    component: "Key",
    label: "Key",
    group: "Security",
    tags: ["access"],
    offLabel: "Key off",
  },
  {
    name: "volume",
    component: "Volume",
    label: "Volume",
    group: "Media",
    tags: ["sound"],
    offLabel: "Volume off",
  },
  {
    name: "eye-closed",
    component: "EyeClosed",
    label: "Eye Closed",
    group: "Objects",
    tags: ["sleep", "hide"],
  },
  {
    name: "cloud",
    component: "Cloud",
    label: "Cloud",
    group: "Nature",
    tags: [],
    offLabel: "Cloud off",
  },
  {
    name: "banknote",
    component: "Banknote",
    label: "Banknote",
    group: "Objects",
    tags: ["money"],
  },
  {
    name: "pill",
    component: "Pill",
    label: "Pill",
    group: "Health",
    tags: ["medicine"],
  },
  {
    name: "link",
    component: "Link",
    label: "Link",
    group: "Objects",
    tags: ["url"],
    offLabel: "Link off",
  },
  {
    name: "ruler",
    component: "Ruler",
    label: "Ruler",
    group: "Objects",
    tags: ["measure"],
  },
  {
    name: "camera",
    component: "Camera",
    label: "Camera",
    group: "Devices",
    tags: ["photo", "snap"],
    offLabel: "Camera off",
  },
  {
    name: "smile",
    base: "circle",
    component: "Smile",
    label: "Smile",
    group: "People",
    tags: ["happy"],
  },
  {
    name: "cloud-upload",
    component: "CloudUpload",
    label: "Cloud Upload",
    group: "Development",
    tags: ["upload"],
  },
  {
    name: "history-forward",
    component: "HistoryForward",
    label: "History Forward",
    group: "Navigation",
    tags: ["restore", "replay"],
  },
  {
    name: "route-off",
    component: "RouteOff",
    label: "Route Off",
    group: "Navigation",
    tags: ["plan", "path", "cancel"],
  },
  {
    name: "text",
    component: "Text",
    label: "Text",
    group: "Typography",
    tags: ["letters", "ab"],
  },
  {
    name: "binary",
    component: "Binary",
    label: "Binary",
    group: "Typography",
    tags: ["data", "code"],
  },
  {
    name: "circle-dashed",
    component: "CircleDashed",
    label: "Circle Dashed",
    group: "Geometry",
    tags: ["pending", "selection"],
  },
  {
    name: "square-arrow-down",
    component: "SquareArrowDown",
    label: "Square Arrow Down",
    group: "Navigation",
    tags: ["download"],
  },
  {
    name: "file-pdf",
    component: "FilePdf",
    label: "File Pdf",
    group: "Files",
    tags: ["document", "pdf"],
  },
  {
    name: "circle-plus",
    component: "CirclePlus",
    label: "circle plus",
    group: "Status",
    tags: ["plus", "state"],
    base: "circle",
  },
  {
    name: "circle-minus",
    component: "CircleMinus",
    label: "circle minus",
    group: "Status",
    tags: ["minus", "state"],
    base: "circle",
  },
  {
    name: "circle-x",
    component: "CircleX",
    label: "circle x",
    group: "Status",
    tags: ["x", "state"],
    base: "circle",
  },
  {
    name: "circle-alert",
    component: "CircleAlert",
    label: "circle alert",
    group: "Status",
    tags: ["alert", "state"],
    base: "circle",
  },
  {
    name: "circle-info",
    component: "CircleInfo",
    label: "circle info",
    group: "Status",
    tags: ["info", "state"],
    base: "circle",
  },
  {
    name: "circle-question",
    component: "CircleQuestion",
    label: "circle question",
    group: "Status",
    tags: ["question", "state"],
    base: "circle",
  },
  {
    name: "circle-play",
    component: "CirclePlay",
    label: "circle play",
    group: "Status",
    tags: ["play", "state"],
    base: "circle",
  },
  {
    name: "circle-pause",
    component: "CirclePause",
    label: "circle pause",
    group: "Status",
    tags: ["pause", "state"],
    base: "circle",
  },
  {
    name: "circle-stop",
    component: "CircleStop",
    label: "circle stop",
    group: "Status",
    tags: ["stop", "state"],
    base: "circle",
  },
  {
    name: "circle-equal",
    component: "CircleEqual",
    label: "circle equal",
    group: "Status",
    tags: ["equal", "state"],
    base: "circle",
  },
  {
    name: "circle-percent",
    component: "CirclePercent",
    label: "circle percent",
    group: "Status",
    tags: ["percent", "state"],
    base: "circle",
  },
  {
    name: "circle-ellipsis",
    component: "CircleEllipsis",
    label: "circle ellipsis",
    group: "Status",
    tags: ["ellipsis", "state"],
    base: "circle",
  },
  {
    name: "circle-arrow-left",
    component: "CircleArrowLeft",
    label: "circle arrow left",
    group: "Status",
    tags: ["left", "state"],
    base: "circle",
  },
  {
    name: "circle-arrow-right",
    component: "CircleArrowRight",
    label: "circle arrow right",
    group: "Status",
    tags: ["right", "state"],
    base: "circle",
  },
  {
    name: "circle-arrow-up",
    component: "CircleArrowUp",
    label: "circle arrow up",
    group: "Status",
    tags: ["up", "state"],
    base: "circle",
  },
  {
    name: "circle-arrow-down",
    component: "CircleArrowDown",
    label: "circle arrow down",
    group: "Status",
    tags: ["down", "state"],
    base: "circle",
  },
  {
    name: "circle-heart",
    component: "CircleHeart",
    label: "circle heart",
    group: "Status",
    tags: ["heart", "state"],
    base: "circle",
  },
  {
    name: "square-plus",
    component: "SquarePlus",
    label: "square plus",
    group: "Layout",
    tags: ["plus", "state"],
    base: "square",
  },
  {
    name: "square-minus",
    component: "SquareMinus",
    label: "square minus",
    group: "Layout",
    tags: ["minus", "state"],
    base: "square",
  },
  {
    name: "square-x",
    component: "SquareX",
    label: "square x",
    group: "Layout",
    tags: ["x", "state"],
    base: "square",
  },
  {
    name: "square-alert",
    component: "SquareAlert",
    label: "square alert",
    group: "Layout",
    tags: ["alert", "state"],
    base: "square",
  },
  {
    name: "square-info",
    component: "SquareInfo",
    label: "square info",
    group: "Layout",
    tags: ["info", "state"],
    base: "square",
  },
  {
    name: "square-question",
    component: "SquareQuestion",
    label: "square question",
    group: "Layout",
    tags: ["question", "state"],
    base: "square",
  },
  {
    name: "square-play",
    component: "SquarePlay",
    label: "square play",
    group: "Layout",
    tags: ["play", "state"],
    base: "square",
  },
  {
    name: "square-pause",
    component: "SquarePause",
    label: "square pause",
    group: "Layout",
    tags: ["pause", "state"],
    base: "square",
  },
  {
    name: "square-stop",
    component: "SquareStop",
    label: "square stop",
    group: "Layout",
    tags: ["stop", "state"],
    base: "square",
  },
  {
    name: "square-equal",
    component: "SquareEqual",
    label: "square equal",
    group: "Layout",
    tags: ["equal", "state"],
    base: "square",
  },
  {
    name: "square-percent",
    component: "SquarePercent",
    label: "square percent",
    group: "Layout",
    tags: ["percent", "state"],
    base: "square",
  },
  {
    name: "square-ellipsis",
    component: "SquareEllipsis",
    label: "square ellipsis",
    group: "Layout",
    tags: ["ellipsis", "state"],
    base: "square",
  },
  {
    name: "square-arrow-left",
    component: "SquareArrowLeft",
    label: "square arrow left",
    group: "Layout",
    tags: ["left", "state"],
    base: "square",
  },
  {
    name: "square-arrow-right",
    component: "SquareArrowRight",
    label: "square arrow right",
    group: "Layout",
    tags: ["right", "state"],
    base: "square",
  },
  {
    name: "square-arrow-up",
    component: "SquareArrowUp",
    label: "square arrow up",
    group: "Layout",
    tags: ["up", "state"],
    base: "square",
  },
  {
    name: "square-check",
    component: "SquareCheck",
    label: "square check",
    group: "Layout",
    tags: ["check", "state"],
    base: "square",
  },
  {
    name: "square-heart",
    component: "SquareHeart",
    label: "square heart",
    group: "Layout",
    tags: ["heart", "state"],
    base: "square",
  },
  {
    name: "file-code",
    component: "FileCode",
    label: "file code",
    group: "Files",
    tags: ["file", "code"],
    base: "file",
  },
  {
    name: "file-braces",
    component: "FileBraces",
    label: "file braces",
    group: "Files",
    tags: ["file", "braces"],
    base: "file",
  },
  {
    name: "file-image",
    component: "FileImage",
    label: "file image",
    group: "Files",
    tags: ["file", "image"],
    base: "file",
  },
  {
    name: "file-music",
    component: "FileMusic",
    label: "file music",
    group: "Files",
    tags: ["file", "music"],
    base: "file",
  },
  {
    name: "file-video",
    component: "FileVideo",
    label: "file video",
    group: "Files",
    tags: ["file", "play"],
    base: "file",
  },
  {
    name: "file-spreadsheet",
    component: "FileSpreadsheet",
    label: "file spreadsheet",
    group: "Files",
    tags: ["file", "grid"],
    base: "file",
  },
  {
    name: "file-chart",
    component: "FileChart",
    label: "file chart",
    group: "Files",
    tags: ["file", "chart"],
    base: "file",
  },
  {
    name: "file-lock",
    component: "FileLock",
    label: "file lock",
    group: "Files",
    tags: ["file", "lock"],
    base: "file",
  },
  {
    name: "file-key",
    component: "FileKey",
    label: "file key",
    group: "Files",
    tags: ["file", "key"],
    base: "file",
  },
  {
    name: "file-check",
    component: "FileCheck",
    label: "file check",
    group: "Files",
    tags: ["file", "check"],
    base: "file",
  },
  {
    name: "file-x",
    component: "FileX",
    label: "file x",
    group: "Files",
    tags: ["file", "x"],
    base: "file",
  },
  {
    name: "file-plus",
    component: "FilePlus",
    label: "file plus",
    group: "Files",
    tags: ["file", "plus"],
    base: "file",
  },
  {
    name: "file-minus",
    component: "FileMinus",
    label: "file minus",
    group: "Files",
    tags: ["file", "minus"],
    base: "file",
  },
  {
    name: "file-question",
    component: "FileQuestion",
    label: "file question",
    group: "Files",
    tags: ["file", "question"],
    base: "file",
  },
  {
    name: "file-alert",
    component: "FileAlert",
    label: "file alert",
    group: "Files",
    tags: ["file", "alert"],
    base: "file",
  },
  {
    name: "file-clock",
    component: "FileClock",
    label: "file clock",
    group: "Files",
    tags: ["file", "clock"],
    base: "file",
  },
  {
    name: "file-search",
    component: "FileSearch",
    label: "file search",
    group: "Files",
    tags: ["file", "search"],
    base: "file",
  },
  {
    name: "file-download",
    component: "FileDownload",
    label: "file download",
    group: "Files",
    tags: ["file", "down"],
    base: "file",
  },
  {
    name: "file-upload",
    component: "FileUpload",
    label: "file upload",
    group: "Files",
    tags: ["file", "up"],
    base: "file",
  },
  {
    name: "file-edit",
    component: "FileEdit",
    label: "file edit",
    group: "Files",
    tags: ["file", "pen"],
    base: "file",
  },
  {
    name: "file-terminal",
    component: "FileTerminal",
    label: "file terminal",
    group: "Files",
    tags: ["file", "terminal"],
    base: "file",
  },
  {
    name: "file-percent",
    component: "FilePercent",
    label: "file percent",
    group: "Files",
    tags: ["file", "percent"],
    base: "file",
  },
  {
    name: "file-list",
    component: "FileList",
    label: "file list",
    group: "Files",
    tags: ["file", "list"],
    base: "file",
  },
  {
    name: "folder-minus",
    component: "FolderMinus",
    label: "folder minus",
    group: "Files",
    tags: ["folder", "minus"],
    base: "folder",
  },
  {
    name: "folder-check",
    component: "FolderCheck",
    label: "folder check",
    group: "Files",
    tags: ["folder", "check"],
    base: "folder",
  },
  {
    name: "folder-x",
    component: "FolderX",
    label: "folder x",
    group: "Files",
    tags: ["folder", "x"],
    base: "folder",
  },
  {
    name: "folder-lock",
    component: "FolderLock",
    label: "folder lock",
    group: "Files",
    tags: ["folder", "lock"],
    base: "folder",
  },
  {
    name: "folder-key",
    component: "FolderKey",
    label: "folder key",
    group: "Files",
    tags: ["folder", "key"],
    base: "folder",
  },
  {
    name: "folder-clock",
    component: "FolderClock",
    label: "folder clock",
    group: "Files",
    tags: ["folder", "clock"],
    base: "folder",
  },
  {
    name: "folder-download",
    component: "FolderDownload",
    label: "folder download",
    group: "Files",
    tags: ["folder", "down"],
    base: "folder",
  },
  {
    name: "folder-upload",
    component: "FolderUpload",
    label: "folder upload",
    group: "Files",
    tags: ["folder", "up"],
    base: "folder",
  },
  {
    name: "folder-heart",
    component: "FolderHeart",
    label: "folder heart",
    group: "Files",
    tags: ["folder", "heart"],
    base: "folder",
  },
  {
    name: "folder-music",
    component: "FolderMusic",
    label: "folder music",
    group: "Files",
    tags: ["folder", "music"],
    base: "folder",
  },
  {
    name: "folder-image",
    component: "FolderImage",
    label: "folder image",
    group: "Files",
    tags: ["folder", "image"],
    base: "folder",
  },
  {
    name: "folder-git",
    component: "FolderGit",
    label: "folder git",
    group: "Files",
    tags: ["folder", "git"],
    base: "folder",
  },
  {
    name: "folder-archive",
    component: "FolderArchive",
    label: "folder archive",
    group: "Files",
    tags: ["folder", "archive"],
    base: "folder",
  },
  {
    name: "folder-cog",
    component: "FolderCog",
    label: "folder cog",
    group: "Files",
    tags: ["folder", "cog"],
    base: "folder",
  },
  {
    name: "message-plus",
    component: "MessagePlus",
    label: "message plus",
    group: "Communication",
    tags: ["message", "plus"],
    base: "message",
  },
  {
    name: "message-minus",
    component: "MessageMinus",
    label: "message minus",
    group: "Communication",
    tags: ["message", "minus"],
    base: "message",
  },
  {
    name: "message-check",
    component: "MessageCheck",
    label: "message check",
    group: "Communication",
    tags: ["message", "check"],
    base: "message",
  },
  {
    name: "message-x",
    component: "MessageX",
    label: "message x",
    group: "Communication",
    tags: ["message", "x"],
    base: "message",
  },
  {
    name: "message-alert",
    component: "MessageAlert",
    label: "message alert",
    group: "Communication",
    tags: ["message", "alert"],
    base: "message",
  },
  {
    name: "message-question",
    component: "MessageQuestion",
    label: "message question",
    group: "Communication",
    tags: ["message", "question"],
    base: "message",
  },
  {
    name: "message-heart",
    component: "MessageHeart",
    label: "message heart",
    group: "Communication",
    tags: ["message", "heart"],
    base: "message",
  },
  {
    name: "message-code",
    component: "MessageCode",
    label: "message code",
    group: "Communication",
    tags: ["message", "code"],
    base: "message",
  },
  {
    name: "message-text",
    component: "MessageText",
    label: "message text",
    group: "Communication",
    tags: ["message", "text"],
    base: "message",
  },
  {
    name: "message-list",
    component: "MessageList",
    label: "message list",
    group: "Communication",
    tags: ["message", "list"],
    base: "message",
  },
  {
    name: "message-ellipsis",
    component: "MessageEllipsis",
    label: "message ellipsis",
    group: "Communication",
    tags: ["message", "ellipsis"],
    base: "message",
  },
  {
    name: "message-lock",
    component: "MessageLock",
    label: "message lock",
    group: "Communication",
    tags: ["message", "lock"],
    base: "message",
  },
  {
    name: "message-music",
    component: "MessageMusic",
    label: "message music",
    group: "Communication",
    tags: ["message", "music"],
    base: "message",
  },
  {
    name: "calendar-check",
    component: "CalendarCheck",
    label: "calendar check",
    group: "Files",
    tags: ["calendar", "check"],
    base: "calendar",
  },
  {
    name: "calendar-minus",
    component: "CalendarMinus",
    label: "calendar minus",
    group: "Files",
    tags: ["calendar", "minus"],
    base: "calendar",
  },
  {
    name: "calendar-search",
    component: "CalendarSearch",
    label: "calendar search",
    group: "Files",
    tags: ["calendar", "search"],
    base: "calendar",
  },
  {
    name: "calendar-clock",
    component: "CalendarClock",
    label: "calendar clock",
    group: "Files",
    tags: ["calendar", "clock"],
    base: "calendar",
  },
  {
    name: "calendar-heart",
    component: "CalendarHeart",
    label: "calendar heart",
    group: "Files",
    tags: ["calendar", "heart"],
    base: "calendar",
  },
  {
    name: "calendar-download",
    component: "CalendarDownload",
    label: "calendar download",
    group: "Files",
    tags: ["calendar", "down"],
    base: "calendar",
  },
  {
    name: "calendar-upload",
    component: "CalendarUpload",
    label: "calendar upload",
    group: "Files",
    tags: ["calendar", "up"],
    base: "calendar",
  },
  {
    name: "calendar-range",
    component: "CalendarRange",
    label: "calendar range",
    group: "Files",
    tags: ["calendar", "range"],
    base: "calendar",
  },
  {
    name: "calendar-days",
    component: "CalendarDays",
    label: "calendar days",
    group: "Files",
    tags: ["calendar", "days"],
    base: "calendar",
  },
  {
    name: "clipboard-list",
    component: "ClipboardList",
    label: "clipboard list",
    group: "Files",
    tags: ["clipboard", "list"],
    base: "clipboard",
  },
  {
    name: "clipboard-plus",
    component: "ClipboardPlus",
    label: "clipboard plus",
    group: "Files",
    tags: ["clipboard", "plus"],
    base: "clipboard",
  },
  {
    name: "clipboard-minus",
    component: "ClipboardMinus",
    label: "clipboard minus",
    group: "Files",
    tags: ["clipboard", "minus"],
    base: "clipboard",
  },
  {
    name: "clipboard-x",
    component: "ClipboardX",
    label: "clipboard x",
    group: "Files",
    tags: ["clipboard", "x"],
    base: "clipboard",
  },
  {
    name: "clipboard-edit",
    component: "ClipboardEdit",
    label: "clipboard edit",
    group: "Files",
    tags: ["clipboard", "pen"],
    base: "clipboard",
  },
  {
    name: "clipboard-clock",
    component: "ClipboardClock",
    label: "clipboard clock",
    group: "Files",
    tags: ["clipboard", "clock"],
    base: "clipboard",
  },
  {
    name: "clipboard-code",
    component: "ClipboardCode",
    label: "clipboard code",
    group: "Files",
    tags: ["clipboard", "code"],
    base: "clipboard",
  },
  {
    name: "clipboard",
    component: "Clipboard",
    label: "clipboard",
    group: "Files",
    tags: ["paste", "copy"],
  },
  {
    name: "shield",
    component: "Shield",
    label: "shield",
    group: "Security",
    tags: ["security", "permission"],
    offLabel: "shield off",
  },
  {
    name: "shield-alert",
    component: "ShieldAlert",
    label: "shield alert",
    group: "Security",
    tags: ["security", "alert"],
    base: "shield",
  },
  {
    name: "shield-x",
    component: "ShieldX",
    label: "shield x",
    group: "Security",
    tags: ["security", "x"],
    base: "shield",
  },
  {
    name: "shield-plus",
    component: "ShieldPlus",
    label: "shield plus",
    group: "Security",
    tags: ["security", "plus"],
    base: "shield",
  },
  {
    name: "shield-minus",
    component: "ShieldMinus",
    label: "shield minus",
    group: "Security",
    tags: ["security", "minus"],
    base: "shield",
  },
  {
    name: "shield-question",
    component: "ShieldQuestion",
    label: "shield question",
    group: "Security",
    tags: ["security", "question"],
    base: "shield",
  },
  {
    name: "shield-lock",
    component: "ShieldLock",
    label: "shield lock",
    group: "Security",
    tags: ["security", "lock"],
    base: "shield",
  },
  {
    name: "shield-key",
    component: "ShieldKey",
    label: "shield key",
    group: "Security",
    tags: ["security", "key"],
    base: "shield",
  },
  {
    name: "shield-heart",
    component: "ShieldHeart",
    label: "shield heart",
    group: "Security",
    tags: ["security", "heart"],
    base: "shield",
  },
  {
    name: "arrow-down",
    component: "ArrowDown",
    label: "arrow down",
    group: "Navigation",
    tags: ["direction", "down"],
  },
  {
    name: "arrow-up-left",
    component: "ArrowUpLeft",
    label: "arrow up left",
    group: "Navigation",
    tags: ["direction", "up-left"],
  },
  {
    name: "arrow-down-left",
    component: "ArrowDownLeft",
    label: "arrow down left",
    group: "Navigation",
    tags: ["direction", "down-left"],
  },
  {
    name: "arrow-down-right",
    component: "ArrowDownRight",
    label: "arrow down right",
    group: "Navigation",
    tags: ["direction", "down-right"],
  },
  {
    name: "chevrons-left",
    component: "ChevronsLeft",
    label: "chevrons left",
    group: "Navigation",
    tags: ["left", "double"],
  },
  {
    name: "arrow-left-to-line",
    component: "ArrowLeftToLine",
    label: "arrow left to line",
    group: "Navigation",
    tags: ["left", "boundary"],
  },
  {
    name: "arrow-left-from-line",
    component: "ArrowLeftFromLine",
    label: "arrow left from line",
    group: "Navigation",
    tags: ["left", "boundary"],
  },
  {
    name: "chevrons-right",
    component: "ChevronsRight",
    label: "chevrons right",
    group: "Navigation",
    tags: ["right", "double"],
  },
  {
    name: "arrow-right-to-line",
    component: "ArrowRightToLine",
    label: "arrow right to line",
    group: "Navigation",
    tags: ["right", "boundary"],
  },
  {
    name: "arrow-right-from-line",
    component: "ArrowRightFromLine",
    label: "arrow right from line",
    group: "Navigation",
    tags: ["right", "boundary"],
  },
  {
    name: "chevrons-up",
    component: "ChevronsUp",
    label: "chevrons up",
    group: "Navigation",
    tags: ["up", "double"],
  },
  {
    name: "arrow-up-to-line",
    component: "ArrowUpToLine",
    label: "arrow up to line",
    group: "Navigation",
    tags: ["up", "boundary"],
  },
  {
    name: "arrow-up-from-line",
    component: "ArrowUpFromLine",
    label: "arrow up from line",
    group: "Navigation",
    tags: ["up", "boundary"],
  },
  {
    name: "chevrons-down",
    component: "ChevronsDown",
    label: "chevrons down",
    group: "Navigation",
    tags: ["down", "double"],
  },
  {
    name: "arrow-down-to-line",
    component: "ArrowDownToLine",
    label: "arrow down to line",
    group: "Navigation",
    tags: ["down", "boundary"],
  },
  {
    name: "arrow-down-from-line",
    component: "ArrowDownFromLine",
    label: "arrow down from line",
    group: "Navigation",
    tags: ["down", "boundary"],
  },
  {
    name: "stop",
    component: "Stop",
    label: "stop",
    group: "Media",
    tags: ["stop"],
  },
  {
    name: "external-link",
    component: "ExternalLink",
    label: "external link",
    group: "Navigation",
    tags: ["external", "link"],
  },
  {
    name: "logout",
    component: "Logout",
    label: "logout",
    group: "Navigation",
    tags: ["logout"],
  },
  {
    name: "login",
    component: "Login",
    label: "login",
    group: "Navigation",
    tags: ["login"],
  },
  {
    name: "undo",
    component: "Undo",
    label: "undo",
    group: "Navigation",
    tags: ["undo"],
  },
  {
    name: "redo",
    component: "Redo",
    label: "redo",
    group: "Navigation",
    tags: ["redo"],
  },
  {
    name: "move-horizontal",
    component: "MoveHorizontal",
    label: "move horizontal",
    group: "Navigation",
    tags: ["move", "horizontal"],
  },
  {
    name: "move-vertical",
    component: "MoveVertical",
    label: "move vertical",
    group: "Navigation",
    tags: ["move", "vertical"],
  },
  {
    name: "arrow-left-right",
    component: "ArrowLeftRight",
    label: "arrow left right",
    group: "Navigation",
    tags: ["arrow", "left", "right"],
  },
  {
    name: "arrow-up-down",
    component: "ArrowUpDown",
    label: "arrow up down",
    group: "Navigation",
    tags: ["arrow", "up", "down"],
  },
  {
    name: "grip-horizontal",
    component: "GripHorizontal",
    label: "grip horizontal",
    group: "Navigation",
    tags: ["grip", "horizontal"],
  },
  {
    name: "grip-vertical",
    component: "GripVertical",
    label: "grip vertical",
    group: "Navigation",
    tags: ["grip", "vertical"],
  },
  {
    name: "ellipsis-vertical",
    component: "EllipsisVertical",
    label: "ellipsis vertical",
    group: "Navigation",
    tags: ["ellipsis", "vertical"],
  },
  {
    name: "server",
    component: "Server",
    label: "server",
    group: "Devices",
    tags: ["provider", "service", "host"],
    offLabel: "server off",
  },
  {
    name: "monitor",
    component: "Monitor",
    label: "monitor",
    group: "Devices",
    tags: ["display", "screen"],
    offLabel: "monitor off",
  },
  {
    name: "laptop",
    component: "Laptop",
    label: "laptop",
    group: "Devices",
    tags: ["computer"],
    offLabel: "laptop off",
  },
  {
    name: "smartphone",
    component: "Smartphone",
    label: "smartphone",
    group: "Devices",
    tags: ["device", "mobile", "touch"],
    offLabel: "smartphone off",
  },
  {
    name: "tablet",
    component: "Tablet",
    label: "tablet",
    group: "Devices",
    tags: ["device", "mobile", "touch"],
  },
  {
    name: "watch",
    component: "Watch",
    label: "watch",
    group: "Devices",
    tags: ["time", "wearable"],
  },
  {
    name: "keyboard",
    component: "Keyboard",
    label: "keyboard",
    group: "Devices",
    tags: ["typing", "input"],
    offLabel: "keyboard off",
  },
  {
    name: "mouse",
    component: "Mouse",
    label: "mouse",
    group: "Devices",
    tags: ["pointer", "input"],
    offLabel: "mouse off",
  },
  {
    name: "touchpad",
    component: "Touchpad",
    label: "touchpad",
    group: "Devices",
    tags: ["input", "trackpad"],
    offLabel: "touchpad off",
  },
  {
    name: "printer",
    component: "Printer",
    label: "printer",
    group: "Devices",
    tags: ["print", "paper"],
    offLabel: "printer off",
  },
  {
    name: "hard-drive",
    component: "HardDrive",
    label: "hard drive",
    group: "Devices",
    tags: ["storage", "disk"],
    offLabel: "hard drive off",
  },
  {
    name: "cpu",
    component: "Cpu",
    label: "cpu",
    group: "Devices",
    tags: ["processor", "chip", "compute"],
  },
  {
    name: "memory-stick",
    component: "MemoryStick",
    label: "memory stick",
    group: "Devices",
    tags: ["ram", "memory", "hardware"],
  },
  {
    name: "router",
    component: "Router",
    label: "router",
    group: "Devices",
    tags: ["network", "gateway"],
  },
  {
    name: "ethernet",
    component: "Ethernet",
    label: "ethernet",
    group: "Devices",
    tags: ["network", "port"],
  },
  {
    name: "usb",
    component: "Usb",
    label: "usb",
    group: "Devices",
    tags: ["port", "connector"],
  },
  {
    name: "power",
    component: "Power",
    label: "power",
    group: "Devices",
    tags: ["on", "shutdown"],
  },
  {
    name: "bluetooth",
    component: "Bluetooth",
    label: "bluetooth",
    group: "Devices",
    tags: ["wireless", "pair"],
    offLabel: "bluetooth off",
  },
  {
    name: "wifi-zero",
    component: "WifiZero",
    label: "wifi zero",
    group: "Devices",
    tags: ["wireless", "network", "zero"],
  },
  {
    name: "wifi-low",
    component: "WifiLow",
    label: "wifi low",
    group: "Devices",
    tags: ["wireless", "network", "low"],
  },
  {
    name: "wifi-high",
    component: "WifiHigh",
    label: "wifi high",
    group: "Devices",
    tags: ["wireless", "network", "high"],
  },
  {
    name: "wifi",
    component: "Wifi",
    label: "wifi",
    group: "Devices",
    tags: ["wireless", "network", ""],
    offLabel: "wifi off",
  },
  {
    name: "battery",
    component: "Battery",
    label: "battery",
    group: "Devices",
    tags: ["power", "charge"],
  },
  {
    name: "battery-low",
    component: "BatteryLow",
    label: "battery low",
    group: "Devices",
    tags: ["power", "charge"],
  },
  {
    name: "battery-medium",
    component: "BatteryMedium",
    label: "battery medium",
    group: "Devices",
    tags: ["power", "charge"],
  },
  {
    name: "battery-full",
    component: "BatteryFull",
    label: "battery full",
    group: "Devices",
    tags: ["power", "charge"],
  },
  {
    name: "battery-charging",
    component: "BatteryCharging",
    label: "battery charging",
    group: "Devices",
    tags: ["power", "charge"],
  },
  {
    name: "lock",
    component: "Lock",
    label: "lock",
    group: "Security",
    tags: ["security", "permission"],
  },
  {
    name: "lock-open",
    component: "LockOpen",
    label: "lock open",
    group: "Security",
    tags: ["security", "permission"],
  },
  {
    name: "lock-keyhole",
    component: "LockKeyhole",
    label: "lock keyhole",
    group: "Security",
    tags: ["security", "permission"],
  },
  {
    name: "fingerprint",
    component: "Fingerprint",
    label: "fingerprint",
    group: "Security",
    tags: ["identity", "biometric"],
  },
  {
    name: "mail",
    component: "Mail",
    label: "mail",
    group: "Communication",
    tags: ["email", "envelope"],
  },
  {
    name: "mail-open",
    component: "MailOpen",
    label: "mail open",
    group: "Communication",
    tags: ["email", "read"],
  },
  {
    name: "inbox",
    component: "Inbox",
    label: "inbox",
    group: "Communication",
    tags: ["messages", "receive"],
  },
  {
    name: "inbox-in",
    component: "InboxIn",
    label: "inbox in",
    group: "Communication",
    tags: ["messages", "receive"],
  },
  {
    name: "inbox-out",
    component: "InboxOut",
    label: "inbox out",
    group: "Communication",
    tags: ["messages", "send"],
  },
  {
    name: "phone",
    component: "Phone",
    label: "phone",
    group: "Communication",
    tags: ["call", "contact"],
  },
  {
    name: "id-card",
    component: "IdCard",
    label: "id card",
    group: "People",
    tags: ["identity", "profile"],
  },
  {
    name: "contact",
    component: "Contact",
    label: "contact",
    group: "People",
    tags: ["address", "person"],
  },
  {
    name: "accessibility",
    component: "Accessibility",
    label: "accessibility",
    group: "People",
    tags: ["access", "person"],
  },
  {
    name: "music",
    component: "Music",
    label: "music",
    group: "Media",
    tags: ["audio", "note"],
  },
  {
    name: "disc",
    component: "Disc",
    label: "disc",
    group: "Media",
    tags: ["audio", "record"],
    base: "circle",
  },
  {
    name: "audio-lines",
    component: "AudioLines",
    label: "audio lines",
    group: "Media",
    tags: ["sound", "waveform"],
  },
  {
    name: "audio-waveform",
    component: "AudioWaveform",
    label: "audio waveform",
    group: "Media",
    tags: ["sound", "wave"],
  },
  {
    name: "equalizer",
    component: "Equalizer",
    label: "equalizer",
    group: "Media",
    tags: ["audio", "levels"],
  },
  {
    name: "film",
    component: "Film",
    label: "film",
    group: "Media",
    tags: ["movie", "video"],
  },
  {
    name: "clapperboard",
    component: "Clapperboard",
    label: "clapperboard",
    group: "Media",
    tags: ["movie", "film"],
  },
  {
    name: "captions",
    component: "Captions",
    label: "captions",
    group: "Media",
    tags: ["subtitle", "accessibility"],
  },
  {
    name: "speaker",
    component: "Speaker",
    label: "speaker",
    group: "Media",
    tags: ["audio", "output"],
  },
  {
    name: "radio",
    component: "Radio",
    label: "radio",
    group: "Media",
    tags: ["audio", "broadcast"],
  },
  {
    name: "volume-1",
    component: "Volume1",
    label: "volume 1",
    group: "Media",
    tags: ["sound", "volume", "low"],
  },
  {
    name: "volume-2",
    component: "Volume2",
    label: "volume 2",
    group: "Media",
    tags: ["sound", "volume", "high"],
  },
  {
    name: "headset",
    component: "Headset",
    label: "headset",
    group: "Media",
    tags: ["audio", "support"],
  },
  {
    name: "image-plus",
    component: "ImagePlus",
    label: "image plus",
    group: "Media",
    tags: ["image", "plus"],
  },
  {
    name: "image-minus",
    component: "ImageMinus",
    label: "image minus",
    group: "Media",
    tags: ["image", "minus"],
  },
  {
    name: "image-upload",
    component: "ImageUpload",
    label: "image upload",
    group: "Media",
    tags: ["image", "up"],
  },
  {
    name: "image-download",
    component: "ImageDownload",
    label: "image download",
    group: "Media",
    tags: ["image", "down"],
  },
  {
    name: "image-check",
    component: "ImageCheck",
    label: "image check",
    group: "Media",
    tags: ["image", "check"],
  },
  {
    name: "image-x",
    component: "ImageX",
    label: "image x",
    group: "Media",
    tags: ["image", "x"],
  },
  {
    name: "image-search",
    component: "ImageSearch",
    label: "image search",
    group: "Media",
    tags: ["image", "search"],
  },
  {
    name: "chart-line",
    component: "ChartLine",
    label: "chart line",
    group: "Data",
    tags: ["trend", "analytics"],
  },
  {
    name: "chart-area",
    component: "ChartArea",
    label: "chart area",
    group: "Data",
    tags: ["analytics", "area"],
  },
  {
    name: "chart-pie",
    component: "ChartPie",
    label: "chart pie",
    group: "Data",
    tags: ["analytics", "proportion"],
  },
  {
    name: "chart-scatter",
    component: "ChartScatter",
    label: "chart scatter",
    group: "Data",
    tags: ["analytics", "points"],
  },
  {
    name: "chart-bar",
    component: "ChartBar",
    label: "chart bar",
    group: "Data",
    tags: ["analytics", "horizontal"],
  },
  {
    name: "trending-up",
    component: "TrendingUp",
    label: "trending up",
    group: "Data",
    tags: ["analytics", "trend", "up"],
  },
  {
    name: "trending-down",
    component: "TrendingDown",
    label: "trending down",
    group: "Data",
    tags: ["analytics", "trend", "down"],
  },
  {
    name: "chart-candlestick",
    component: "ChartCandlestick",
    label: "chart candlestick",
    group: "Data",
    tags: ["finance", "price"],
  },
  {
    name: "number-0",
    component: "Number0",
    label: "number 0",
    group: "Typography",
    tags: ["0", "character", "number"],
  },
  {
    name: "number-1",
    component: "Number1",
    label: "number 1",
    group: "Typography",
    tags: ["1", "character", "number"],
  },
  {
    name: "number-2",
    component: "Number2",
    label: "number 2",
    group: "Typography",
    tags: ["2", "character", "number"],
  },
  {
    name: "number-3",
    component: "Number3",
    label: "number 3",
    group: "Typography",
    tags: ["3", "character", "number"],
  },
  {
    name: "number-4",
    component: "Number4",
    label: "number 4",
    group: "Typography",
    tags: ["4", "character", "number"],
  },
  {
    name: "number-5",
    component: "Number5",
    label: "number 5",
    group: "Typography",
    tags: ["5", "character", "number"],
  },
  {
    name: "number-6",
    component: "Number6",
    label: "number 6",
    group: "Typography",
    tags: ["6", "character", "number"],
  },
  {
    name: "number-7",
    component: "Number7",
    label: "number 7",
    group: "Typography",
    tags: ["7", "character", "number"],
  },
  {
    name: "number-8",
    component: "Number8",
    label: "number 8",
    group: "Typography",
    tags: ["8", "character", "number"],
  },
  {
    name: "number-9",
    component: "Number9",
    label: "number 9",
    group: "Typography",
    tags: ["9", "character", "number"],
  },
  {
    name: "letter-a",
    component: "LetterA",
    label: "letter a",
    group: "Typography",
    tags: ["A", "character", "letter"],
  },
  {
    name: "letter-b",
    component: "LetterB",
    label: "letter b",
    group: "Typography",
    tags: ["B", "character", "letter"],
  },
  {
    name: "letter-c",
    component: "LetterC",
    label: "letter c",
    group: "Typography",
    tags: ["C", "character", "letter"],
  },
  {
    name: "letter-d",
    component: "LetterD",
    label: "letter d",
    group: "Typography",
    tags: ["D", "character", "letter"],
  },
  {
    name: "letter-e",
    component: "LetterE",
    label: "letter e",
    group: "Typography",
    tags: ["E", "character", "letter"],
  },
  {
    name: "letter-f",
    component: "LetterF",
    label: "letter f",
    group: "Typography",
    tags: ["F", "character", "letter"],
  },
  {
    name: "letter-g",
    component: "LetterG",
    label: "letter g",
    group: "Typography",
    tags: ["G", "character", "letter"],
  },
  {
    name: "letter-h",
    component: "LetterH",
    label: "letter h",
    group: "Typography",
    tags: ["H", "character", "letter"],
  },
  {
    name: "letter-i",
    component: "LetterI",
    label: "letter i",
    group: "Typography",
    tags: ["I", "character", "letter"],
  },
  {
    name: "letter-j",
    component: "LetterJ",
    label: "letter j",
    group: "Typography",
    tags: ["J", "character", "letter"],
  },
  {
    name: "letter-k",
    component: "LetterK",
    label: "letter k",
    group: "Typography",
    tags: ["K", "character", "letter"],
  },
  {
    name: "letter-l",
    component: "LetterL",
    label: "letter l",
    group: "Typography",
    tags: ["L", "character", "letter"],
  },
  {
    name: "letter-m",
    component: "LetterM",
    label: "letter m",
    group: "Typography",
    tags: ["M", "character", "letter"],
  },
  {
    name: "letter-n",
    component: "LetterN",
    label: "letter n",
    group: "Typography",
    tags: ["N", "character", "letter"],
  },
  {
    name: "letter-o",
    component: "LetterO",
    label: "letter o",
    group: "Typography",
    tags: ["O", "character", "letter"],
  },
  {
    name: "letter-p",
    component: "LetterP",
    label: "letter p",
    group: "Typography",
    tags: ["P", "character", "letter"],
  },
  {
    name: "letter-q",
    component: "LetterQ",
    label: "letter q",
    group: "Typography",
    tags: ["Q", "character", "letter"],
  },
  {
    name: "letter-r",
    component: "LetterR",
    label: "letter r",
    group: "Typography",
    tags: ["R", "character", "letter"],
  },
  {
    name: "letter-s",
    component: "LetterS",
    label: "letter s",
    group: "Typography",
    tags: ["S", "character", "letter"],
  },
  {
    name: "letter-t",
    component: "LetterT",
    label: "letter t",
    group: "Typography",
    tags: ["T", "character", "letter"],
  },
  {
    name: "letter-u",
    component: "LetterU",
    label: "letter u",
    group: "Typography",
    tags: ["U", "character", "letter"],
  },
  {
    name: "letter-v",
    component: "LetterV",
    label: "letter v",
    group: "Typography",
    tags: ["V", "character", "letter"],
  },
  {
    name: "letter-w",
    component: "LetterW",
    label: "letter w",
    group: "Typography",
    tags: ["W", "character", "letter"],
  },
  {
    name: "letter-x",
    component: "LetterX",
    label: "letter x",
    group: "Typography",
    tags: ["X", "character", "letter"],
  },
  {
    name: "letter-y",
    component: "LetterY",
    label: "letter y",
    group: "Typography",
    tags: ["Y", "character", "letter"],
  },
  {
    name: "letter-z",
    component: "LetterZ",
    label: "letter z",
    group: "Typography",
    tags: ["Z", "character", "letter"],
  },
  {
    name: "italic",
    component: "Italic",
    label: "italic",
    group: "Typography",
    tags: ["format", "text"],
  },
  {
    name: "underline",
    component: "Underline",
    label: "underline",
    group: "Typography",
    tags: ["format", "text"],
  },
  {
    name: "heading",
    component: "Heading",
    label: "heading",
    group: "Typography",
    tags: ["text", "title"],
  },
  {
    name: "heading-1",
    component: "Heading1",
    label: "heading 1",
    group: "Typography",
    tags: ["text", "title", "1"],
  },
  {
    name: "heading-2",
    component: "Heading2",
    label: "heading 2",
    group: "Typography",
    tags: ["text", "title", "2"],
  },
  {
    name: "heading-3",
    component: "Heading3",
    label: "heading 3",
    group: "Typography",
    tags: ["text", "title", "3"],
  },
  {
    name: "heading-4",
    component: "Heading4",
    label: "heading 4",
    group: "Typography",
    tags: ["text", "title", "4"],
  },
  {
    name: "heading-5",
    component: "Heading5",
    label: "heading 5",
    group: "Typography",
    tags: ["text", "title", "5"],
  },
  {
    name: "heading-6",
    component: "Heading6",
    label: "heading 6",
    group: "Typography",
    tags: ["text", "title", "6"],
  },
  {
    name: "align-left",
    component: "AlignLeft",
    label: "align left",
    group: "Typography",
    tags: ["text", "alignment", "left"],
  },
  {
    name: "align-center",
    component: "AlignCenter",
    label: "align center",
    group: "Typography",
    tags: ["text", "alignment", "center"],
  },
  {
    name: "align-right",
    component: "AlignRight",
    label: "align right",
    group: "Typography",
    tags: ["text", "alignment", "right"],
  },
  {
    name: "align-justify",
    component: "AlignJustify",
    label: "align justify",
    group: "Typography",
    tags: ["text", "alignment", "justify"],
  },
  {
    name: "indent",
    component: "Indent",
    label: "indent",
    group: "Typography",
    tags: ["text", "list"],
  },
  {
    name: "outdent",
    component: "Outdent",
    label: "outdent",
    group: "Typography",
    tags: ["text", "list"],
  },
  {
    name: "list-ordered",
    component: "ListOrdered",
    label: "list ordered",
    group: "Typography",
    tags: ["list", "ordered"],
  },
  {
    name: "list-filter",
    component: "ListFilter",
    label: "list filter",
    group: "Typography",
    tags: ["list", "filter"],
  },
  {
    name: "list-plus",
    component: "ListPlus",
    label: "list plus",
    group: "Typography",
    tags: ["list", "plus"],
  },
  {
    name: "list-minus",
    component: "ListMinus",
    label: "list minus",
    group: "Typography",
    tags: ["list", "minus"],
  },
  {
    name: "list-x",
    component: "ListX",
    label: "list x",
    group: "Typography",
    tags: ["list", "x"],
  },
  {
    name: "list-tree",
    component: "ListTree",
    label: "list tree",
    group: "Typography",
    tags: ["list", "tree"],
  },
  {
    name: "list-todo",
    component: "ListTodo",
    label: "list todo",
    group: "Typography",
    tags: ["list", "todo"],
  },
  {
    name: "quote",
    component: "Quote",
    label: "quote",
    group: "Typography",
    tags: ["text", "quotation"],
  },
  {
    name: "text-cursor",
    component: "TextCursor",
    label: "text cursor",
    group: "Typography",
    tags: ["typing", "caret"],
  },
  {
    name: "text-select",
    component: "TextSelect",
    label: "text select",
    group: "Typography",
    tags: ["selection", "text"],
  },
  {
    name: "text-quote",
    component: "TextQuote",
    label: "text quote",
    group: "Typography",
    tags: ["citation", "quote"],
  },
  {
    name: "hash",
    component: "Hash",
    label: "hash",
    group: "Typography",
    tags: ["number", "tag"],
  },
  {
    name: "ampersand",
    component: "Ampersand",
    label: "ampersand",
    group: "Typography",
    tags: ["and", "symbol"],
  },
  {
    name: "parentheses",
    component: "Parentheses",
    label: "parentheses",
    group: "Typography",
    tags: ["code", "punctuation"],
  },
  {
    name: "brackets",
    component: "Brackets",
    label: "brackets",
    group: "Typography",
    tags: ["code", "punctuation"],
  },
  {
    name: "backslash",
    component: "Backslash",
    label: "backslash",
    group: "Typography",
    tags: ["symbol"],
  },
  {
    name: "slash-forward",
    component: "SlashForward",
    label: "slash forward",
    group: "Typography",
    tags: ["symbol"],
  },
  {
    name: "dot",
    component: "Dot",
    label: "dot",
    group: "Typography",
    tags: ["point", "punctuation"],
  },
  {
    name: "superscript",
    component: "Superscript",
    label: "superscript",
    group: "Typography",
    tags: ["text", "power"],
  },
  {
    name: "subscript",
    component: "Subscript",
    label: "subscript",
    group: "Typography",
    tags: ["text", "power"],
  },
  {
    name: "spell-check",
    component: "SpellCheck",
    label: "spell check",
    group: "Typography",
    tags: ["text", "spelling"],
  },
  {
    name: "languages",
    component: "Languages",
    label: "languages",
    group: "Typography",
    tags: ["language", "translate"],
  },
  {
    name: "letter-spacing",
    component: "LetterSpacing",
    label: "letter spacing",
    group: "Typography",
    tags: ["typography", "tracking"],
  },
  {
    name: "line-height",
    component: "LineHeight",
    label: "line height",
    group: "Typography",
    tags: ["typography", "leading"],
  },
  {
    name: "filter",
    component: "Filter",
    label: "filter",
    group: "Navigation",
    tags: ["funnel", "refine"],
  },
  {
    name: "sort-ascending",
    component: "SortAscending",
    label: "sort ascending",
    group: "Navigation",
    tags: ["order", "ascending"],
  },
  {
    name: "sort-descending",
    component: "SortDescending",
    label: "sort descending",
    group: "Navigation",
    tags: ["order", "descending"],
  },
  {
    name: "sliders-horizontal",
    component: "SlidersHorizontal",
    label: "sliders horizontal",
    group: "Layout",
    tags: ["settings", "controls"],
  },
  {
    name: "sliders-vertical",
    component: "SlidersVertical",
    label: "sliders vertical",
    group: "Layout",
    tags: ["settings", "controls"],
  },
  {
    name: "toggle-off",
    component: "ToggleOff",
    label: "toggle off",
    group: "Layout",
    tags: ["switch", "disabled"],
  },
  {
    name: "toggle-on",
    component: "ToggleOn",
    label: "toggle on",
    group: "Layout",
    tags: ["switch", "enabled"],
  },
  {
    name: "grid-2",
    component: "Grid2",
    label: "grid 2",
    group: "Layout",
    tags: ["layout", "grid"],
  },
  {
    name: "grid-3",
    component: "Grid3",
    label: "grid 3",
    group: "Layout",
    tags: ["layout", "grid"],
  },
  {
    name: "rows",
    component: "Rows",
    label: "rows",
    group: "Layout",
    tags: ["layout", "pane"],
  },
  {
    name: "panels-top",
    component: "PanelsTop",
    label: "panels top",
    group: "Layout",
    tags: ["layout", "pane"],
  },
  {
    name: "panels-bottom",
    component: "PanelsBottom",
    label: "panels bottom",
    group: "Layout",
    tags: ["layout", "pane"],
  },
  {
    name: "sidebar-open",
    component: "SidebarOpen",
    label: "sidebar open",
    group: "Layout",
    tags: ["layout", "pane"],
  },
  {
    name: "sidebar-close",
    component: "SidebarClose",
    label: "sidebar close",
    group: "Layout",
    tags: ["layout", "pane"],
  },
  {
    name: "file-diff",
    component: "FileDiff",
    label: "file diff",
    group: "Files",
    tags: ["patch", "changes"],
    base: "file",
  },
  {
    name: "file-output",
    component: "FileOutput",
    label: "file output",
    group: "Files",
    tags: ["result", "export"],
    base: "file",
  },
  {
    name: "git-fork",
    component: "GitFork",
    label: "git fork",
    group: "Development",
    tags: ["branch", "fork", "session"],
  },
  {
    name: "git-commit",
    component: "GitCommit",
    label: "git commit",
    group: "Development",
    tags: ["version", "revision"],
  },
  {
    name: "git-pull-request",
    component: "GitPullRequest",
    label: "git pull request",
    group: "Development",
    tags: ["review", "merge"],
  },
  {
    name: "workflow",
    component: "Workflow",
    label: "workflow",
    group: "Development",
    tags: ["plan", "steps", "flow"],
  },
  {
    name: "network",
    component: "Network",
    label: "network",
    group: "Development",
    tags: ["http", "connection", "protocol"],
  },
  {
    name: "web-search",
    component: "WebSearch",
    label: "web search",
    group: "Development",
    tags: ["internet", "search"],
  },
  {
    name: "cloud-download",
    component: "CloudDownload",
    label: "cloud download",
    group: "Development",
    tags: ["fetch", "receive"],
  },
  {
    name: "memory-search",
    component: "MemorySearch",
    label: "memory search",
    group: "Development",
    tags: ["recall", "knowledge", "search"],
  },
  {
    name: "tool-search",
    component: "ToolSearch",
    label: "tool search",
    group: "Development",
    tags: ["tools", "discovery"],
  },
  {
    name: "binary-code",
    component: "BinaryCode",
    label: "binary code",
    group: "Development",
    tags: ["encoding", "bits"],
  },
  {
    name: "regex",
    component: "Regex",
    label: "regex",
    group: "Development",
    tags: ["pattern", "expression"],
  },
  {
    name: "database-backup",
    component: "DatabaseBackup",
    label: "database backup",
    group: "Development",
    tags: ["storage", "snapshot"],
  },
  {
    name: "hexagon",
    component: "Hexagon",
    label: "hexagon",
    group: "Geometry",
    tags: ["shape", "hexagon"],
  },
  {
    name: "pentagon",
    component: "Pentagon",
    label: "pentagon",
    group: "Geometry",
    tags: ["shape", "pentagon"],
  },
  {
    name: "triangle",
    component: "Triangle",
    label: "triangle",
    group: "Geometry",
    tags: ["shape", "triangle"],
  },
  {
    name: "diamond",
    component: "Diamond",
    label: "diamond",
    group: "Geometry",
    tags: ["shape", "diamond"],
  },
  {
    name: "octagon",
    component: "Octagon",
    label: "octagon",
    group: "Geometry",
    tags: ["shape", "octagon"],
  },
  {
    name: "cone",
    component: "Cone",
    label: "cone",
    group: "Geometry",
    tags: ["shape", "solid"],
  },
  {
    name: "cylinder",
    component: "Cylinder",
    label: "cylinder",
    group: "Geometry",
    tags: ["shape", "solid"],
  },
  {
    name: "layers",
    component: "Layers",
    label: "layers",
    group: "Layout",
    tags: ["stack", "sheets"],
  },
  {
    name: "crop",
    component: "Crop",
    label: "crop",
    group: "Layout",
    tags: ["image", "trim"],
  },
  {
    name: "scissors",
    component: "Scissors",
    label: "scissors",
    group: "Objects",
    tags: ["cut", "edit"],
  },
  {
    name: "eraser",
    component: "Eraser",
    label: "eraser",
    group: "Objects",
    tags: ["remove", "edit"],
  },
  {
    name: "brush",
    component: "Brush",
    label: "brush",
    group: "Objects",
    tags: ["paint", "draw"],
  },
  {
    name: "palette",
    component: "Palette",
    label: "palette",
    group: "Objects",
    tags: ["colors", "theme"],
  },
  {
    name: "home",
    component: "Home",
    label: "home",
    group: "Objects",
    tags: ["house", "start"],
  },
  {
    name: "building",
    component: "Building",
    label: "building",
    group: "Objects",
    tags: ["office", "organization"],
  },
  {
    name: "briefcase",
    component: "Briefcase",
    label: "briefcase",
    group: "Objects",
    tags: ["work", "business"],
  },
  {
    name: "shopping-bag",
    component: "ShoppingBag",
    label: "shopping bag",
    group: "Objects",
    tags: ["store", "purchase"],
  },
  {
    name: "gift",
    component: "Gift",
    label: "gift",
    group: "Objects",
    tags: ["present", "reward"],
  },
  {
    name: "coffee",
    component: "Coffee",
    label: "coffee",
    group: "Objects",
    tags: ["break", "drink"],
  },
  {
    name: "heart",
    component: "Heart",
    label: "heart",
    group: "Objects",
    tags: ["favorite", "like"],
  },
  {
    name: "hand",
    component: "Hand",
    label: "hand",
    group: "People",
    tags: ["stop", "gesture"],
  },
  {
    name: "sunrise",
    component: "Sunrise",
    label: "sunrise",
    group: "Nature",
    tags: ["morning", "weather"],
  },
  {
    name: "snowflake",
    component: "Snowflake",
    label: "snowflake",
    group: "Nature",
    tags: ["cold", "winter"],
  },
  {
    name: "wind",
    component: "Wind",
    label: "wind",
    group: "Nature",
    tags: ["air", "weather"],
  },
  {
    name: "droplet",
    component: "Droplet",
    label: "droplet",
    group: "Nature",
    tags: ["water", "liquid"],
  },
  {
    name: "leaf",
    component: "Leaf",
    label: "leaf",
    group: "Nature",
    tags: ["plant", "nature"],
  },
  {
    name: "mountain",
    component: "Mountain",
    label: "mountain",
    group: "Nature",
    tags: ["landscape", "outdoor"],
  },
  {
    name: "compass",
    component: "Compass",
    label: "compass",
    group: "Navigation",
    tags: ["direction", "explore"],
    base: "circle",
  },
  {
    name: "navigation",
    component: "Navigation",
    label: "navigation",
    group: "Navigation",
    tags: ["direction", "location"],
  },
  {
    name: "milestone",
    component: "Milestone",
    label: "milestone",
    group: "Navigation",
    tags: ["roadmap", "stage"],
  },
  {
    name: "book-text",
    component: "BookText",
    label: "book text",
    group: "Files",
    tags: ["book", "text"],
    base: "book",
  },
  {
    name: "book-code",
    component: "BookCode",
    label: "book code",
    group: "Files",
    tags: ["book", "code"],
    base: "book",
  },
  {
    name: "book-check",
    component: "BookCheck",
    label: "book check",
    group: "Files",
    tags: ["book", "check"],
    base: "book",
  },
  {
    name: "book-lock",
    component: "BookLock",
    label: "book lock",
    group: "Files",
    tags: ["book", "lock"],
    base: "book",
  },
  {
    name: "book-heart",
    component: "BookHeart",
    label: "book heart",
    group: "Files",
    tags: ["book", "heart"],
    base: "book",
  },
  {
    name: "book-search",
    component: "BookSearch",
    label: "book search",
    group: "Files",
    tags: ["book", "search"],
    base: "book",
  },
  {
    name: "bookmark-plus",
    component: "BookmarkPlus",
    label: "bookmark plus",
    group: "Objects",
    tags: ["bookmark", "plus"],
    base: "bookmark",
  },
  {
    name: "bookmark-minus",
    component: "BookmarkMinus",
    label: "bookmark minus",
    group: "Objects",
    tags: ["bookmark", "minus"],
    base: "bookmark",
  },
  {
    name: "bookmark-check",
    component: "BookmarkCheck",
    label: "bookmark check",
    group: "Objects",
    tags: ["bookmark", "check"],
    base: "bookmark",
  },
  {
    name: "bookmark-x",
    component: "BookmarkX",
    label: "bookmark x",
    group: "Objects",
    tags: ["bookmark", "x"],
    base: "bookmark",
  },
  {
    name: "user-plus",
    component: "UserPlus",
    label: "user plus",
    group: "People",
    tags: ["account", "person", "plus"],
  },
  {
    name: "user-minus",
    component: "UserMinus",
    label: "user minus",
    group: "People",
    tags: ["account", "person", "minus"],
  },
  {
    name: "user-check",
    component: "UserCheck",
    label: "user check",
    group: "People",
    tags: ["account", "person", "check"],
  },
  {
    name: "user-x",
    component: "UserX",
    label: "user x",
    group: "People",
    tags: ["account", "person", "x"],
  },
  {
    name: "user-search",
    component: "UserSearch",
    label: "user search",
    group: "People",
    tags: ["account", "person", "search"],
  },
  {
    name: "user-lock",
    component: "UserLock",
    label: "user lock",
    group: "People",
    tags: ["account", "person", "lock"],
  },
  {
    name: "user-round",
    component: "UserRound",
    label: "user round",
    group: "People",
    tags: ["profile", "person"],
  },
  {
    name: "circle-user",
    component: "CircleUser",
    label: "circle user",
    group: "People",
    tags: ["avatar", "profile"],
    base: "circle",
  },
  {
    name: "smile-plus",
    component: "SmilePlus",
    label: "smile plus",
    group: "People",
    tags: ["reaction", "add"],
  },
  {
    name: "frown",
    component: "Frown",
    label: "frown",
    group: "People",
    tags: ["unhappy", "reaction"],
    base: "circle",
  },
  {
    name: "meh",
    component: "Meh",
    label: "meh",
    group: "People",
    tags: ["neutral", "reaction"],
    base: "circle",
  },
  {
    name: "rocket",
    component: "Rocket",
    label: "rocket",
    group: "Objects",
    tags: ["launch", "start"],
  },
  {
    name: "trophy",
    component: "Trophy",
    label: "trophy",
    group: "Objects",
    tags: ["achievement", "win"],
  },
  {
    name: "medal",
    component: "Medal",
    label: "medal",
    group: "Objects",
    tags: ["award", "achievement"],
  },
  {
    name: "ticket",
    component: "Ticket",
    label: "ticket",
    group: "Objects",
    tags: ["pass", "admission"],
  },
  {
    name: "wallet",
    component: "Wallet",
    label: "wallet",
    group: "Objects",
    tags: ["payment", "money"],
  },
  {
    name: "credit-card",
    component: "CreditCard",
    label: "credit card",
    group: "Objects",
    tags: ["payment", "billing"],
  },
  {
    name: "coins",
    component: "Coins",
    label: "coins",
    group: "Objects",
    tags: ["money", "cost"],
  },
  {
    name: "scale",
    component: "Scale",
    label: "scale",
    group: "Objects",
    tags: ["balance", "law"],
  },
  {
    name: "lightbulb-flash",
    component: "LightbulbFlash",
    label: "lightbulb flash",
    group: "Objects",
    tags: ["idea", "inspiration"],
  },
  {
    name: "wand",
    component: "Wand",
    label: "wand",
    group: "Objects",
    tags: ["magic", "enhance"],
  },
  {
    name: "magnet",
    component: "Magnet",
    label: "magnet",
    group: "Objects",
    tags: ["snap", "attract"],
  },
  {
    name: "key-round",
    component: "KeyRound",
    label: "key round",
    group: "Security",
    tags: ["credentials", "secret"],
  },
  {
    name: "scan",
    component: "Scan",
    label: "scan",
    group: "Layout",
    tags: ["capture", "inspect"],
  },
  {
    name: "qr-code",
    component: "QRCode",
    label: "qr code",
    group: "Development",
    tags: ["code", "scan"],
  },
  {
    name: "barcode",
    component: "Barcode",
    label: "barcode",
    group: "Development",
    tags: ["code", "scan"],
  },
  {
    name: "test-tube",
    component: "TestTube",
    label: "test tube",
    group: "Development",
    tags: ["experiment", "test"],
  },
  {
    name: "function",
    component: "Function",
    label: "function",
    group: "Development",
    tags: ["code", "formula"],
  },
  {
    name: "variable",
    component: "Variable",
    label: "variable",
    group: "Development",
    tags: ["code", "value"],
  },
  {
    name: "code-slash",
    component: "CodeSlash",
    label: "code slash",
    group: "Development",
    tags: ["source", "syntax"],
  },
  {
    name: "web-window",
    component: "WebWindow",
    label: "web window",
    group: "Development",
    tags: ["browser", "application"],
  },
  {
    name: "web-window-code",
    component: "WebWindowCode",
    label: "web window code",
    group: "Development",
    tags: ["browser", "developer"],
  },
  {
    name: "terminal-square",
    component: "TerminalSquare",
    label: "terminal square",
    group: "Development",
    tags: ["console", "command"],
    base: "square",
  },
  {
    name: "component",
    component: "Component",
    label: "component",
    group: "Development",
    tags: ["module", "parts"],
  },
  {
    name: "unplug",
    component: "Unplug",
    label: "unplug",
    group: "Development",
    tags: ["disconnect", "connection"],
  },
  {
    name: "cloud-rain",
    component: "CloudRain",
    label: "cloud rain",
    group: "Nature",
    tags: ["weather", "rain"],
  },
  {
    name: "cloud-lightning",
    component: "CloudLightning",
    label: "cloud lightning",
    group: "Nature",
    tags: ["weather", "storm"],
  },
  {
    name: "umbrella",
    component: "Umbrella",
    label: "umbrella",
    group: "Nature",
    tags: ["rain", "shelter"],
  },
  {
    name: "thermometer",
    component: "Thermometer",
    label: "thermometer",
    group: "Nature",
    tags: ["temperature", "weather"],
  },
  {
    name: "tree",
    component: "Tree",
    label: "tree",
    group: "Nature",
    tags: ["plant", "forest"],
  },
  {
    name: "flower",
    component: "Flower",
    label: "flower",
    group: "Nature",
    tags: ["bloom", "plant"],
  },
  {
    name: "globe-location",
    component: "GlobeLocation",
    label: "globe location",
    group: "Navigation",
    tags: ["place", "world"],
  },
  {
    name: "plane",
    component: "Plane",
    label: "plane",
    group: "Travel",
    tags: ["flight", "transport"],
  },
  {
    name: "car",
    component: "Car",
    label: "car",
    group: "Travel",
    tags: ["vehicle", "transport"],
  },
  {
    name: "train",
    component: "Train",
    label: "train",
    group: "Travel",
    tags: ["rail", "transport"],
  },
  {
    name: "bike",
    component: "Bike",
    label: "bike",
    group: "Travel",
    tags: ["cycle", "transport"],
  },
  {
    name: "ship",
    component: "Ship",
    label: "ship",
    group: "Travel",
    tags: ["boat", "transport"],
  },
  {
    name: "luggage",
    component: "Luggage",
    label: "luggage",
    group: "Travel",
    tags: ["journey", "bag"],
  },
  {
    name: "heart-pulse",
    component: "HeartPulse",
    label: "heart pulse",
    group: "Health",
    tags: ["health", "heartbeat"],
  },
  {
    name: "stethoscope",
    component: "Stethoscope",
    label: "stethoscope",
    group: "Health",
    tags: ["medical", "diagnostic"],
  },
  {
    name: "syringe",
    component: "Syringe",
    label: "syringe",
    group: "Health",
    tags: ["medical", "injection"],
  },
  {
    name: "hospital",
    component: "Hospital",
    label: "hospital",
    group: "Health",
    tags: ["medical", "building"],
  },
  {
    name: "rotate-left",
    component: "RotateLeft",
    label: "rotate left",
    group: "Navigation",
    tags: ["rotate", "turn"],
  },
  {
    name: "rotate-right",
    component: "RotateRight",
    label: "rotate right",
    group: "Navigation",
    tags: ["rotate", "turn"],
  },
  {
    name: "repeat",
    component: "Repeat",
    label: "repeat",
    group: "Media",
    tags: ["loop", "playback"],
  },
  {
    name: "shuffle",
    component: "Shuffle",
    label: "shuffle",
    group: "Media",
    tags: ["random", "playback"],
  },
  {
    name: "skip-forward",
    component: "SkipForward",
    label: "skip forward",
    group: "Media",
    tags: ["next", "playback"],
  },
  {
    name: "fast-forward",
    component: "FastForward",
    label: "fast forward",
    group: "Media",
    tags: ["playback", "forward"],
  },
  {
    name: "rewind",
    component: "Rewind",
    label: "rewind",
    group: "Media",
    tags: ["playback", "backward"],
  },
  {
    name: "picture-in-picture",
    component: "PictureInPicture",
    label: "picture in picture",
    group: "Media",
    tags: ["video", "mini-player"],
  },
  {
    name: "tv",
    component: "Tv",
    label: "tv",
    group: "Devices",
    tags: ["television", "screen"],
  },
  {
    name: "webcam",
    component: "Webcam",
    label: "webcam",
    group: "Devices",
    tags: ["video", "camera"],
  },
  {
    name: "gamepad",
    component: "Gamepad",
    label: "gamepad",
    group: "Devices",
    tags: ["game", "controller"],
  },
  {
    name: "file-archive",
    component: "FileArchive",
    label: "Archive file",
    group: "Files",
    tags: ["zip", "compressed", "archive"],
    base: "file",
  },
];
