import { memo } from "react";
import {
  Activity,
  ClipboardList,
  ToolSearch,
  MemorySearch,
  CloudDownload,
  WebSearch,
  FileOutput,
  FileImage,
  FileCode,
  FileDiff,
  Grid2,
  GitFork,
  Workflow,
  Network,
  Server,
  Shield,
  ExternalLink,
  Stop,
  Alert,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BellOff,
  Blocks,
  Book,
  BookOpen,
  Bot,
  Brain,
  BrainOff,
  Bug,
  CalendarPlus,
  CalendarClock,
  CalendarX,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleDot,
  CircleInfo,
  CircleX,
  ClipboardCheck,
  Clock,
  CloseAll,
  CloseOthers,
  Code,
  Columns,
  Command,
  Compose,
  Copy,
  Crosshair,
  Diff,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileBraces,
  FileEdit,
  FileMusic,
  FilePdf,
  FileSpreadsheet,
  FileText,
  FileVideo,
  Flag,
  Fold,
  Folder,
  FolderOpen,
  FolderSearch,
  Gauge,
  Globe,
  History,
  Image,
  Keyboard,
  Library,
  Lightning,
  List,
  ListChecks,
  Map,
  Maximize,
  Message,
  Moon,
  PackageSearch,
  Palette,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pause,
  Pencil,
  Pin,
  PinOff,
  Play,
  Plug,
  PlugOff,
  Plus,
  Quote,
  CircleQuestion,
  Refresh,
  Replace,
  ScrollText,
  Search,
  Send,
  Settings,
  Share,
  SkipBack,
  Sparkle,
  Sparkles,
  Star,
  Strikethrough,
  Sun,
  Target,
  Terminal,
  TextSearch,
  ThumbsDown,
  ThumbsUp,
  Trash,
  UnfoldHorizontal,
  UnfoldVertical,
  User,
  Users,
  Webhook,
  WrapText,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
  type IconComponent,
  type IconProps,
} from "@flame/icons/react";
import { useUiFontSize } from "@/lib/appearance";
import { iconSizePx } from "@/lib/iconScale";
import type { IconSize } from "@/lib/iconScale";

const ICON_MAP = {
  server: Server,
  network: Network,
  workflow: Workflow,
  fork: GitFork,
  "grid-2": Grid2,
  "file-diff": FileDiff,
  "file-text": FileText,
  "file-image": FileImage,
  "file-code": FileCode,
  "file-output": FileOutput,
  "file-archive": FileArchive,
  "file-braces": FileBraces,
  "file-edit": FileEdit,
  "file-music": FileMusic,
  "file-pdf": FilePdf,
  "file-spreadsheet": FileSpreadsheet,
  "file-video": FileVideo,
  "web-search": WebSearch,
  "cloud-download": CloudDownload,
  "memory-search": MemorySearch,
  "tool-search": ToolSearch,
  "clipboard-list": ClipboardList,
  activity: Activity,
  search: Search,
  plus: Plus,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  chat: Message,
  folder: Folder,
  "folder-open": FolderOpen,
  code: Code,
  terminal: Terminal,
  file: File,
  send: Send,
  stop: Stop,
  play: Play,
  pause: Pause,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  share: Share,
  more: Ellipsis,
  x: X,
  check: Check,
  circle: Circle,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  info: CircleInfo,
  "circle-x": CircleX,
  globe: Globe,
  book: Book,
  history: History,
  tool: Wrench,
  sparkle: Sparkle,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  edit: Pencil,
  image: Image,
  command: Command,
  keyboard: Keyboard,
  palette: Palette,
  quote: Quote,
  "panel-l": PanelLeft,
  "panel-r": PanelRight,
  user: User,
  spark: Sparkles,
  "skip-back": SkipBack,
  fold: Fold,
  columns: Columns,
  gauge: Gauge,
  open: ExternalLink,
  compose: Compose,
  "close-others": CloseOthers,
  "close-all": CloseAll,
  maximize: Maximize,
  diff: Diff,
  list: List,
  chart: ChartColumn,
  clock: Clock,
  "calendar-clock": CalendarClock,
  bell: Bell,
  blocks: Blocks,
  lightning: Lightning,
  bug: Bug,
  shield: Shield,
  loop: Refresh,
  copy: Copy,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  trash: Trash,
  alert: Alert,
  eye: Eye,
  "folder-search": FolderSearch,
  download: Download,
  bot: Bot,
  question: CircleQuestion,
  star: Star,
  scroll: ScrollText,
  replace: Replace,
  "text-search": TextSearch,
  webhook: Webhook,
  library: Library,
  "book-open": BookOpen,
  paperclip: Paperclip,
  users: Users,
  map: Map,
  "list-checks": ListChecks,
  flag: Flag,
  brain: Brain,
  "package-search": PackageSearch,
  archive: Archive,
  "calendar-plus": CalendarPlus,
  "calendar-x": CalendarX,
  target: Target,
  crosshair: Crosshair,
  "clipboard-check": ClipboardCheck,
  "unfold-horizontal": UnfoldHorizontal,
  "unfold-vertical": UnfoldVertical,
  "wrap-text": WrapText,

  "bell-off": BellOff,
  "brain-off": BrainOff,
  "eye-off": EyeOff,
  pin: Pin,
  "pin-off": PinOff,
  plug: Plug,
  "plug-off": PlugOff,
  strikethrough: Strikethrough,
} satisfies Record<string, IconComponent>;

export type IconName = keyof typeof ICON_MAP;

export const ICON_NAMES: ReadonlySet<IconName> = new Set(Object.keys(ICON_MAP) as IconName[]);

export function knownIconName(value: string | null | undefined): IconName | undefined {
  return value != null && ICON_NAMES.has(value as IconName) ? (value as IconName) : undefined;
}

interface Props {
  name: IconName;
  size?: IconSize;
  style?: IconProps["style"];
  className?: string;
  full?: boolean;
}

export const Icon = memo(function Icon({ name, size = "sm", style, className, full }: Props) {
  const fontSize = useUiFontSize();
  const pixels = iconSizePx(size, fontSize);
  const Glyph = ICON_MAP[name];
  return (
    <Glyph
      aria-hidden="true"
      data-icon-name={name}
      data-glyph={full ? "full" : undefined}
      className={className}
      size={pixels}
      style={style}
    />
  );
});
