import * as stylex from "@stylexjs/stylex";
import { color, leading, motion, radius, space, surface, weight } from "@/styles/tokens.stylex";

export const viewStyles = stylex.create({
  gutter: { paddingInline: "var(--reading-gutter-wide)" },

  rowPad: { paddingBlock: space.s2 },
  rowPadTall: { paddingBlock: space.s2_5 },
  padBlockSm: { paddingBlock: space.s1 },
  sectionPad: { paddingBottom: space.s1 },
  sectionLabel: { paddingBlock: space.s2 },

  diffFileHeader: {
    display: "flex",
    height: space.s8,
    width: "100%",
    minWidth: 0,
    alignItems: "center",
    gap: space.s2,
    borderWidth: 0,
    backgroundColor: surface.sunken,
    paddingInline: space.s3,
    textAlign: "left",
    color: { default: color.fgMuted, ":hover": color.fg },
    transitionProperty: "color",
    transitionDuration: motion.color,
    transitionTimingFunction: motion.easeState,
  },

  pressRow: {
    display: "flex",
    width: "100%",
    minWidth: 0,
    alignItems: "flex-start",
    gap: space.s2_5,
    textAlign: "left",
  },
  rowTop: { display: "flex", alignItems: "flex-start", gap: space.s2_5 },
  wash: {
    transitionProperty: "background-color",
    transitionTimingFunction: motion.easeState,
    backgroundColor: { default: null, ":hover": surface.hover },
  },
  glyphTop: { marginTop: space.s0_5 },
  origin: { marginTop: space.s1, color: color.fgFaint },
  actions: { display: "flex", flexShrink: 0, alignItems: "center", gap: space.s2 },
  actionsTight: { display: "flex", flexShrink: 0, alignItems: "center", gap: space.s0_5 },
  body: { color: color.fg, lineHeight: leading.body, overflowWrap: "break-word" },
  metaLine: { marginTop: space.s1, display: "flex", alignItems: "center", gap: space.s2 },
  formLine: { marginTop: space.s2, display: "flex", alignItems: "center", gap: space.s2 },
  filterLine: { display: "flex", alignItems: "center", gap: space.s1 },
  pinLine: { display: "flex", flexShrink: 0, alignItems: "center", gap: space.s1 },
  dotTop: { marginTop: space.s1_5 },
  subLine: {
    marginTop: space.s0_5,
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: space.s1_5,
  },
  dismissed: { opacity: "var(--state-receded)" },

  lineBaseline: { display: "flex", alignItems: "baseline", gap: space.s2, minWidth: 0 },
  subject: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  lineTop: { display: "flex", alignItems: "flex-start", gap: space.s3, minWidth: 0 },
  splitLine: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "baseline",
    gap: space.s2,
  },
  titleLine: {
    display: "flex",
    flexWrap: "wrap",
    minWidth: 0,
    alignItems: "center",
    gap: space.s2,
  },

  pushEnd: { marginInlineStart: "auto" },

  title: { color: color.fg, fontWeight: weight.medium },
  description: {
    marginTop: space.s0_5,
    color: color.fgMuted,
    lineHeight: leading.body,
    overflowWrap: "break-word",
  },
  subCaption: { marginTop: space.s0_5, color: color.fgFaint },
  dotSep: { lineHeight: 1, color: color.fgFaint },
  subCaptionMuted: { marginTop: space.s0_5, color: color.fgMuted },

  entry: {
    display: "flex",
    alignItems: "baseline",
    gap: space.s2,
    fontFamily: "var(--font-mono)",
  },
  entryPlain: { display: "flex", alignItems: "baseline", gap: space.s2 },
  statusPad: { paddingTop: space.s1, paddingBottom: space.s2 },
  padBottom: { paddingBottom: space.s2 },
  groupPad: { paddingBlock: space.s1_5 },
  afterTitle: { marginTop: space.s0_5 },
  matchCount: { marginInlineStart: space.s1_5, fontWeight: weight.regular, color: color.fgFaint },
  matchRow: {
    display: "grid",
    width: "100%",
    gridTemplateColumns: "calc(var(--spacing) * 11) minmax(0, 1fr)",
    gap: space.s2,
    borderRadius: radius.xs,
    paddingBlock: "1px",
    paddingRight: space.s1,
    fontFamily: "var(--font-mono)",
    lineHeight: leading.body,
  },
  lineNumber: { textAlign: "right", color: color.fgFaint, userSelect: "none" },
  discloseRow: {
    display: "grid",
    gridTemplateColumns: "calc(var(--spacing) * 3.5) minmax(0, 1fr) auto",
    alignItems: "center",
    gap: space.s2,
    borderWidth: 0,
    backgroundColor: "transparent",
    textAlign: "left",
  },
  editorInset: { paddingBottom: space.s3, paddingLeft: space.s10 },
});

export const timelineStyles = stylex.create({
  glyph: { marginTop: space.s1, flexShrink: 0, color: color.fgFaint },
  kind: { color: color.fg, fontWeight: weight.medium },
  mark: { marginTop: space.s1, flexShrink: 0, lineHeight: 1 },
  stamp: {
    marginTop: space.s0_5,
    flexShrink: 0,
    fontFamily: "var(--font-mono)",
    color: color.fgFaint,
  },
  duration: { minWidth: "calc(var(--spacing) * 12)", textAlign: "right" },
  runHeader: {
    display: "flex",
    minHeight: space.s10,
    alignItems: "flex-start",
    gap: space.s2,
    borderRadius: radius.card,
    backgroundColor: surface.sunken,
    marginInline: space.s2,
    paddingBlock: space.s2,
    paddingLeft: "calc(var(--reading-gutter-wide) - var(--spacing) * 2)",
    paddingRight:
      "calc(var(--reading-gutter-wide) - var(--spacing) * 2 - (var(--control-height-md) - var(--icon-md)) / 2)",
  },
  runDetail: {
    marginTop: space.s0_5,
    display: "flex",
    minWidth: 0,
    gap: space.s2,
    color: color.fgMuted,
  },
  groupGap: { marginTop: space.s3, paddingTop: space.s1 },
  nested: {
    borderLeftWidth: "var(--control-edge-width)",
    borderLeftStyle: "solid",
    borderLeftColor: surface.field,
    paddingLeft: space.s2,
  },
});

const indentStyles = stylex.create({
  d0: {},
  d1: { marginLeft: space.s3 },
  d2: { marginLeft: space.s6 },
  d3: { marginLeft: space.s9 },
  d4: { marginLeft: space.s12 },
  d5: { marginLeft: space.s16 },
});

export const indent = [
  indentStyles.d0,
  indentStyles.d1,
  indentStyles.d2,
  indentStyles.d3,
  indentStyles.d4,
  indentStyles.d5,
] as const;

export const codeStyles = stylex.create({
  sheet: { paddingBlock: space.s2, fontFamily: "var(--font-mono)", lineHeight: leading.relaxed },
  gutter: { textAlign: "right", color: color.fgFaint, userSelect: "none" },
  wrap: { minWidth: 0, whiteSpace: "pre-wrap", overflowWrap: "anywhere" },
  hunk: {
    marginTop: { default: space.s2_5, ":first-child": 0 },
    borderWidth: 0,
    backgroundColor: surface.sunken,
    paddingInline: space.s3,
    paddingBlock: space.s1,
    color: color.fgFaint,
    overflowWrap: "anywhere",
  },
  sideBySide: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
  blank: { backgroundColor: surface.sunken },

  lineRow: { display: "grid", alignItems: "flex-start", paddingInline: space.s3 },
  gutterOne: { gridTemplateColumns: "44px minmax(0, 1fr)", gap: space.s2 },
  gutterPair: { gridTemplateColumns: "36px 36px minmax(0, 1fr)", gap: space.s1_5 },
  gutterSign: { gridTemplateColumns: "34px 16px minmax(0, 1fr)", gap: space.s1_5 },
  lineMeta: { textAlign: "right", userSelect: "none" },
  signMeta: { textAlign: "center", userSelect: "none" },
  targetLine: { backgroundColor: surface.accentWash },

  rowAdded: {
    backgroundColor: "var(--color-diff-added-tint)",
    boxShadow: "var(--shadow-diff-added-spine)",
  },
  rowDeleted: {
    backgroundColor: "var(--color-diff-deleted-tint)",
    boxShadow: "var(--shadow-diff-deleted-spine)",
  },
  metaAdded: { color: "var(--color-diff-added-meta)" },
  metaDeleted: { color: "var(--color-diff-deleted-meta)" },
  metaContext: { color: color.fgFaint },

  fileCard: {
    marginBottom: space.s2,
    marginTop: { default: null, ":first-child": space.s2 },
    overflow: "clip",
    borderRadius: radius.card,
    borderWidth: "var(--hairline-width)",
    borderStyle: "solid",
    borderColor: surface.field,
  },
  fileCardLast: { marginBottom: 0 },
  note: {
    margin: 0,
    paddingInline: space.s3,
    paddingBlock: space.s2,
    fontFamily: "var(--font-mono)",
    color: color.fgFaint,
  },
});
