import * as stylex from "@stylexjs/stylex";
import { color, corner, leading, radius, space, surface, weight } from "@/styles/tokens.stylex";

export const fx = stylex.create({
  pane: { display: "flex", minHeight: 0, flex: 1, flexDirection: "column" },
  paneRow: { display: "flex", minHeight: 0, flex: 1 },
  scroller: {
    display: "flex",
    minHeight: 0,
    flex: 1,
    flexDirection: "column",
    gap: space.s0_5,
    overflowY: "auto",
    paddingInline: space.s2,
    paddingTop: space.s2,
  },
  listPad: { paddingInline: space.s2, paddingTop: space.s2 },
  column: { display: "flex", flexDirection: "column" },
  columnTight: { display: "flex", flexDirection: "column", gap: space.s0_5 },
  line: { display: "flex", alignItems: "center" },
  contents: { display: "contents" },
  relative: { position: "relative" },
  fill: { flex: 1 },

  listHead: {
    paddingInline: space.s2,
    paddingBottom: space.s1,
    fontWeight: weight.semibold,
    color: color.fg,
  },
  listFoot: {
    paddingInline: space.s4,
    paddingBottom: space.s3,
    lineHeight: leading.body,
    color: color.fgFaint,
  },
  footGap: { minHeight: space.s4 },

  ink: { color: color.fg },
  soft: { color: color.fgSoft },
  muted: { color: color.fgMuted },
  faint: { color: color.fgFaint },
  medium: { fontWeight: weight.medium },
  semibold: { fontWeight: weight.semibold },
  mono: { fontFamily: "var(--font-mono)", letterSpacing: 0 },
  figures: { fontVariantNumeric: "tabular-nums" },
  truncate: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  relaxed: { lineHeight: leading.relaxed },

  specimenLabel: {
    paddingInline: space.s2,
    paddingBottom: space.s1,
    fontWeight: weight.medium,
    letterSpacing: "0.025em",
    textTransform: "uppercase",
    color: color.fgFaint,
  },
  specimenLabelFlush: {
    fontWeight: weight.medium,
    letterSpacing: "0.025em",
    textTransform: "uppercase",
    color: color.fgFaint,
  },
  card: {
    borderRadius: radius.lg,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: surface.field,
    backgroundColor: surface.surface,
    padding: space.s4,
  },
  cardGrid: {
    marginTop: space.s8,
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: space.s4,
  },

  measure: {
    marginInline: "auto",
    display: "flex",
    width: "100%",
    maxWidth: "var(--content-max)",
    flex: 1,
    flexDirection: "column",
    paddingTop: space.s10,
    paddingInline: {
      default: "var(--density-column-gutter)",
      "@media (min-width: 640px)": "var(--density-column-gutter-wide)",
    },
  },
  heading: {
    marginTop: space.s2,
    fontWeight: weight.semibold,
    lineHeight: leading.tight,
    color: color.fg,
  },
  headingLoose: {
    marginTop: space.s4,
    fontWeight: weight.semibold,
    lineHeight: leading.tight,
    color: color.fg,
  },
  lede: { marginTop: space.s3, maxWidth: "62ch", lineHeight: leading.relaxed, color: color.fgSoft },
  afterHeading: { marginTop: space.s2, lineHeight: leading.relaxed, color: color.fgMuted },
  row: { marginTop: space.s3, display: "flex", alignItems: "center", gap: space.s2 },
  rowBaseline: {
    marginTop: space.s3,
    display: "flex",
    alignItems: "flex-end",
    gap: space.s3,
    color: color.fg,
  },
  captionRow: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
    paddingInline: space.s2,
    paddingBottom: space.s2,
  },

  editorBox: {
    minHeight: "calc(var(--spacing) * 20)",
    paddingInline: "var(--density-composer-editor-start)",
    paddingTop: "var(--density-composer-editor-top)",
    paddingBottom: "var(--density-composer-editor-bottom)",
    lineHeight: leading.relaxed,
    color: color.fg,
  },
  footerBox: {
    display: "flex",
    alignItems: "center",
    gap: space.s1,
    paddingInline: "var(--density-composer-footer)",
    paddingBottom: "var(--density-composer-footer)",
  },
  minRail: { minWidth: space.s2, flex: 1 },
  minField: { minHeight: space.s8, flex: 1 },
  hairline: { height: space.s4, flexShrink: 0 },

  emptyBox: {
    margin: "auto",
    display: "flex",
    maxWidth: "520px",
    flexDirection: "column",
    alignItems: "center",
    paddingInline: space.s8,
    textAlign: "center",
  },
  emptyGlyph: {
    display: "grid",
    height: space.s10,
    width: space.s10,
    placeItems: "center",
    backgroundColor: surface.surface2,
    color: color.fgMuted,
  },
});

export { corner };
