package main

import (
	"fmt"
	"reflect"
	"slices"
	"sort"
	"strconv"
	"strings"

	"github.com/Tangerg/flame/runtime/internal/contractcatalog"
	"github.com/Tangerg/flame/runtime/internal/contractshape"
	"github.com/Tangerg/flame/runtime/internal/delivery"
	"github.com/Tangerg/flame/runtime/internal/delivery/dispatch"
	"github.com/Tangerg/flame/runtime/protocol"
)

// The Go wire validator enforces registered constraints at Runtime boundaries.
//
// It replaces hand-written request checks and also guards typed output boundaries.
// Generating Go, schema, and TypeScript checks from the same registry prevents
// the three representations from declaring different constraints.
//
// Four rule sources, and none restates another's job:
//
//   - the declared value constraints (a string that may not be empty, a number
//     that may not be zero) — reflection cannot see these;
//   - closed-enum membership, DERIVED from the enum's own declared value set. Go's
//     decoder puts any string into a named string type, so without this check a
//     bogus tag reaches a use case or client;
//   - registered union variants;
//   - registered conditional field rules.

// validatorFile is written into the protocol package, beside the shapes it checks.
const validatorFile = "wire_constraints.generated.go"

type validatorRuleIndex struct {
	values  map[reflect.Type][]dispatch.FieldConstraint
	unions  map[reflect.Type]dispatch.UnionSpec
	objects map[reflect.Type][]dispatch.ConditionalRule
}

func newValidators(registry *delivery.Registry, shapes *dispatch.Shapes, walked *schemaSet) string {
	var out strings.Builder
	out.WriteString("// Code generated by cmd/contractgen. DO NOT EDIT.\n\n")
	out.WriteString("package protocol\n")

	rules := newValidatorRuleIndex(shapes)
	for _, target := range validatorTargets(registry, shapes, walked) {
		writeValidator(&out, target, rules.checks(target))
	}
	return out.String()
}

func newValidatorRuleIndex(shapes *dispatch.Shapes) validatorRuleIndex {
	rules := validatorRuleIndex{
		values:  make(map[reflect.Type][]dispatch.FieldConstraint),
		unions:  make(map[reflect.Type]dispatch.UnionSpec),
		objects: make(map[reflect.Type][]dispatch.ConditionalRule),
	}
	for _, spec := range shapes.ValueConstraints() {
		rules.values[spec.GoType] = append(rules.values[spec.GoType], spec.Constraints...)
	}
	for _, spec := range shapes.Unions() {
		rules.unions[spec.GoType] = spec
	}
	for _, spec := range shapes.Constraints() {
		rules.objects[spec.GoType] = append(rules.objects[spec.GoType], spec.Rules...)
	}
	return rules
}

func (r validatorRuleIndex) checks(target reflect.Type) []string {
	return validatorChecks(target, inheritedValueConstraints(target, r.values), r.unions[target], r.objects[target])
}

func validatorTargets(registry *delivery.Registry, shapes *dispatch.Shapes, walked *schemaSet) []reflect.Type {
	// Request roots come first in method-registration order. Registered unions,
	// conditional objects and value-constrained roots follow in declaration order.
	// This makes every Registry-authored shape rule reachable by the Go generator,
	// including DTOs that only travel from server to client.
	var targets []reflect.Type
	written := make(map[reflect.Type]bool)
	for _, meta := range registry.Metas() {
		targets = appendValidatorTarget(targets, written, meta.Params)
	}
	for _, spec := range shapes.Unions() {
		targets = appendValidatorTarget(targets, written, spec.GoType)
	}
	for _, spec := range shapes.Constraints() {
		targets = appendValidatorTarget(targets, written, spec.GoType)
	}
	for _, spec := range shapes.ValueConstraints() {
		targets = appendValidatorTarget(targets, written, spec.GoType)
	}
	for _, target := range reachableProtocolStructs(walked) {
		targets = appendValidatorTarget(targets, written, target)
	}
	return targets
}

func appendValidatorTarget(targets []reflect.Type, written map[reflect.Type]bool, target reflect.Type) []reflect.Type {
	if target == nil || target.Name() == "" || written[target] {
		return targets
	}
	written[target] = true
	return append(targets, target)
}

func reachableProtocolStructs(walked *schemaSet) []reflect.Type {
	// Closed enums are derived from field types rather than registered against
	// their carrier objects. Include every reachable protocol struct so a DTO
	// whose only local rule is enum membership receives the same Go validator as
	// its JSON Schema and TypeScript projections.
	protocolPackage := reflect.TypeFor[protocol.Session]().PkgPath()
	definitionNames := make([]string, 0, len(walked.origin))
	for name := range walked.origin {
		definitionNames = append(definitionNames, name)
	}
	sort.Strings(definitionNames)
	targets := make([]reflect.Type, 0, len(definitionNames))
	for _, name := range definitionNames {
		target := walked.origin[name]
		if target.Kind() != reflect.Struct || target.PkgPath() != protocolPackage ||
			target.Name() == "" || strings.Contains(target.Name(), "[") {
			continue
		}
		targets = append(targets, target)
	}
	return targets
}

func writeValidator(out *strings.Builder, target reflect.Type, checks []string) {
	if len(checks) == 0 {
		return
	}
	fmt.Fprintf(out, "\nfunc (%s %s) ValidateWire() error {\n", receiverName(target), target.Name())
	fmt.Fprintf(out, "\treturn collectWireViolations(%q,\n", target.Name())
	for _, check := range checks {
		fmt.Fprintf(out, "\t\t%s,\n", check)
	}
	out.WriteString("\t)\n}\n")
}

// inheritedValueConstraints returns the constraints visible on an encoded
// shape, including fields flattened from embedded DTOs. encoding/json does not
// preserve the embedded object boundary, so a generated Go validator that only
// checked the outer declaration would disagree with the schema and TypeScript
// validators for the exact same JSON frame.
func inheritedValueConstraints(shape reflect.Type, declared map[reflect.Type][]dispatch.FieldConstraint) []dispatch.FieldConstraint {
	owners := append([]reflect.Type{shape}, contractshape.Embeds(shape)...)
	var out []dispatch.FieldConstraint
	for _, owner := range owners {
		for _, constraint := range declared[owner] {
			if !slices.Contains(out, constraint) {
				out = append(out, constraint)
			}
		}
	}
	return out
}

// receiverName is the identifier the generated method binds its receiver to.
// Generated methods follow the same rule as hand-written ones — the lowercased
// first letter of the type — so a shape does not answer to two different names
// depending on which half of the file a reader is in.
func receiverName(shape reflect.Type) string {
	if shape.Name() == "" {
		panic("contractgen: cannot name a receiver for an unnamed shape")
	}
	return strings.ToLower(shape.Name()[:1])
}

// validatorChecks builds every frame-local check registered for one wire shape.
func validatorChecks(
	shape reflect.Type,
	constraints []dispatch.FieldConstraint,
	union dispatch.UnionSpec,
	rules []dispatch.ConditionalRule,
) []string {
	recv := receiverName(shape)
	checks := make([]string, 0, len(constraints))
	for _, constraint := range constraints {
		if check := constraintCheck(shape, constraint, union); check != "" {
			checks = append(checks, check)
		}
	}
	checks = append(checks, enumChecks(shape)...)
	checks = append(checks, unionChecks(union, recv)...)
	checks = append(checks, objectChecks(rules, recv)...)
	return checks
}

func constraintCheck(
	shape reflect.Type,
	constraint dispatch.FieldConstraint,
	union dispatch.UnionSpec,
) string {
	selector, leaf, found := contractshape.GoPath(shape, constraint.Field)
	if !found {
		panic(fmt.Sprintf("contractgen: %s has no field %q", shape.Name(), constraint.Field))
	}
	switch constraint.Kind {
	case dispatch.ConstraintNonEmpty, dispatch.ConstraintMaxLength, dispatch.ConstraintIdentity,
		dispatch.ConstraintPrefix, dispatch.ConstraintPattern:
		return textConstraintCheck(shape, selector, leaf, constraint, union)
	case dispatch.ConstraintPositive, dispatch.ConstraintNonNegative,
		dispatch.ConstraintMinimum, dispatch.ConstraintMaximum:
		return numericConstraintCheck(shape, selector, leaf, constraint)
	case dispatch.ConstraintNonEmptyItems, dispatch.ConstraintUniqueItems,
		dispatch.ConstraintMinItems, dispatch.ConstraintMaxItems,
		dispatch.ConstraintMaxItemLength, dispatch.ConstraintIdentityItems,
		dispatch.ConstraintPrefixItems, dispatch.ConstraintPatternItems:
		return itemConstraintCheck(shape, selector, leaf, constraint)
	case dispatch.ConstraintNonEmptyProperties, dispatch.ConstraintMaxPropertyNameLength,
		dispatch.ConstraintIdentityPropertyNames:
		return propertyConstraintCheck(shape, selector, constraint)
	default:
		return unsupportedConstraintCheck(shape, constraint)
	}
}

func textConstraintCheck(
	shape reflect.Type,
	selector string,
	leaf contractshape.Field,
	constraint dispatch.FieldConstraint,
	union dispatch.UnionSpec,
) string {
	field := strconv.Quote(constraint.Field)
	switch constraint.Kind {
	case dispatch.ConstraintNonEmpty:
		return nonEmptyConstraintCheck(shape, selector, leaf, constraint, union)
	case dispatch.ConstraintMaxLength:
		validatorName := "maxLength"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalMaxLength"
		}
		return fmt.Sprintf(
			"%s(%s, %s, %d)",
			validatorName,
			field,
			stringExpr(shape, selector, leaf.Type),
			constraint.Limit,
		)
	case dispatch.ConstraintIdentity:
		validatorName := "identity"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalIdentity"
		}
		return fmt.Sprintf("%s(%s, %s)", validatorName, field, stringExpr(shape, selector, leaf.Type))
	case dispatch.ConstraintPrefix:
		return prefixConstraintCheck(shape, selector, leaf, constraint)
	case dispatch.ConstraintPattern:
		return patternConstraintCheck(shape, selector, leaf, constraint)
	default:
		return unsupportedConstraintCheck(shape, constraint)
	}
}

func nonEmptyConstraintCheck(
	shape reflect.Type,
	selector string,
	leaf contractshape.Field,
	constraint dispatch.FieldConstraint,
	union dispatch.UnionSpec,
) string {
	// A non-pointer scalar cannot distinguish an omitted JSON property from its
	// zero value after decoding. When a union branch owns the property's
	// requiredness, requiredWhen below already rejects that zero value in the
	// branch where it is required and accepts it where the property is forbidden.
	// An unconditional requiredText would reject every other legal branch.
	if leaf.Optional && leaf.Type.Kind() != reflect.Pointer && unionRequiresField(union, constraint.Field) {
		return ""
	}
	validatorName := "requiredText"
	if leaf.Optional && leaf.Type.Kind() == reflect.Pointer {
		validatorName = "optionalText"
	}
	return fmt.Sprintf(
		"%s(%s, %s)",
		validatorName,
		strconv.Quote(constraint.Field),
		stringExpr(shape, selector, leaf.Type),
	)
}

func prefixConstraintCheck(
	shape reflect.Type,
	selector string,
	leaf contractshape.Field,
	constraint dispatch.FieldConstraint,
) string {
	validatorName := "requiredTextPrefix"
	if leaf.Type.Kind() == reflect.Pointer {
		validatorName = "optionalTextPointerPrefix"
	}
	return fmt.Sprintf(
		"%s(%s, %s, %s)",
		validatorName,
		strconv.Quote(constraint.Field),
		stringExpr(shape, selector, leaf.Type),
		strconv.Quote(constraint.Value),
	)
}

func patternConstraintCheck(
	shape reflect.Type,
	selector string,
	leaf contractshape.Field,
	constraint dispatch.FieldConstraint,
) string {
	validatorName := "requiredTextPattern"
	if leaf.Type.Kind() == reflect.Pointer {
		validatorName = "optionalTextPointerPattern"
	} else if leaf.Optional {
		validatorName = "optionalTextPattern"
	}
	return fmt.Sprintf(
		"%s(%s, %s, %s)",
		validatorName,
		strconv.Quote(constraint.Field),
		stringExpr(shape, selector, leaf.Type),
		strconv.Quote(constraint.Value),
	)
}

func numericConstraintCheck(
	shape reflect.Type,
	selector string,
	leaf contractshape.Field,
	constraint dispatch.FieldConstraint,
) string {
	field := strconv.Quote(constraint.Field)
	ref := receiverName(shape) + "." + selector
	switch constraint.Kind {
	case dispatch.ConstraintPositive:
		validatorName := "positiveNumber"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalPositiveNumber"
		} else if leaf.Optional {
			validatorName = "optionalPositiveScalarNumber"
		}
		return fmt.Sprintf("%s(%s, %s)", validatorName, field, ref)
	case dispatch.ConstraintNonNegative:
		validatorName := "nonNegativeNumber"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalNonNegativeNumber"
		}
		return fmt.Sprintf("%s(%s, %s)", validatorName, field, ref)
	case dispatch.ConstraintMinimum:
		return fmt.Sprintf("minimumNumber(%s, %s, %d)", field, ref, constraint.Limit)
	case dispatch.ConstraintMaximum:
		validatorName := "maximumNumber"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalMaximumNumber"
		}
		return fmt.Sprintf("%s(%s, %s, %d)", validatorName, field, ref, constraint.Limit)
	default:
		return unsupportedConstraintCheck(shape, constraint)
	}
}

func itemConstraintCheck(
	shape reflect.Type,
	selector string,
	leaf contractshape.Field,
	constraint dispatch.FieldConstraint,
) string {
	field := strconv.Quote(constraint.Field)
	ref := receiverName(shape) + "." + selector
	switch constraint.Kind {
	case dispatch.ConstraintNonEmptyItems:
		validatorName := "requiredItems"
		if leaf.Optional {
			validatorName = "nonEmptyItems"
		}
		return fmt.Sprintf("%s(%s, %s)", validatorName, field, ref)
	case dispatch.ConstraintUniqueItems:
		validatorName := "uniqueItems"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalUniqueItems"
		}
		return fmt.Sprintf("%s(%s, %s)", validatorName, field, ref)
	case dispatch.ConstraintMinItems:
		return fmt.Sprintf("optionalMinItems(%s, %s, %d)", field, ref, constraint.Limit)
	case dispatch.ConstraintMaxItems:
		validatorName := "maxItems"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalMaxItems"
		}
		return fmt.Sprintf("%s(%s, %s, %d)", validatorName, field, ref, constraint.Limit)
	case dispatch.ConstraintMaxItemLength:
		validatorName := "maxItemLength"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalMaxItemLength"
		}
		return fmt.Sprintf("%s(%s, %s, %d)", validatorName, field, ref, constraint.Limit)
	case dispatch.ConstraintIdentityItems:
		return fmt.Sprintf("identityItems(%s, %s)", field, ref)
	case dispatch.ConstraintPrefixItems:
		return fmt.Sprintf(
			"textPrefixItems(%s, %s, %s)",
			field,
			ref,
			strconv.Quote(constraint.Value),
		)
	case dispatch.ConstraintPatternItems:
		validatorName := "textPatternItems"
		if leaf.Type.Kind() == reflect.Pointer {
			validatorName = "optionalTextPatternItems"
		}
		return fmt.Sprintf(
			"%s(%s, %s, %s)",
			validatorName,
			field,
			ref,
			strconv.Quote(constraint.Value),
		)
	default:
		return unsupportedConstraintCheck(shape, constraint)
	}
}

func propertyConstraintCheck(
	shape reflect.Type,
	selector string,
	constraint dispatch.FieldConstraint,
) string {
	field := strconv.Quote(constraint.Field)
	ref := receiverName(shape) + "." + selector
	switch constraint.Kind {
	case dispatch.ConstraintNonEmptyProperties:
		return fmt.Sprintf("nonEmptyProperties(%s, %s)", field, ref)
	case dispatch.ConstraintMaxPropertyNameLength:
		return fmt.Sprintf("maxPropertyNameLength(%s, %s, %d)", field, ref, constraint.Limit)
	case dispatch.ConstraintIdentityPropertyNames:
		return fmt.Sprintf("identityPropertyNames(%s, %s)", field, ref)
	default:
		return unsupportedConstraintCheck(shape, constraint)
	}
}

func unsupportedConstraintCheck(shape reflect.Type, constraint dispatch.FieldConstraint) string {
	panic(fmt.Sprintf(
		"contractgen: %s.%s uses unsupported constraint %s",
		shape.Name(),
		constraint.Field,
		constraint.Kind,
	))
}

func unionRequiresField(union dispatch.UnionSpec, field string) bool {
	if union.GoType == nil {
		return false
	}
	for _, variant := range union.Variants {
		if slices.Contains(variant.Required, field) {
			return true
		}
	}
	if pattern := union.PatternVariant; pattern != nil {
		return slices.Contains(pattern.Required, field)
	}
	return false
}

func enumChecks(shape reflect.Type) []string {
	recv := receiverName(shape)
	var checks []string
	for _, field := range contractshape.Fields(shape) {
		if values, found := contractcatalog.EnumValues(field.Type); found {
			checks = append(checks, fmt.Sprintf("closedEnum(%s, string(%s.%s), %s, %t)",
				strconv.Quote(field.Name), recv, field.GoName, valueList(values), field.Optional))
			continue
		}
		if field.Type.Kind() == reflect.Slice {
			if values, found := contractcatalog.EnumValues(field.Type.Elem()); found {
				checks = append(checks, fmt.Sprintf("closedEnumItems(%s, %s.%s, %s)",
					strconv.Quote(field.Name), recv, field.GoName, valueList(values)))
			}
		}
	}
	return checks
}

func unionChecks(union dispatch.UnionSpec, recv string) []string {
	if union.GoType == nil {
		return nil
	}
	paths := unionPaths(union)
	var checks []string
	if pattern := union.PatternVariant; pattern != nil {
		checks = append(checks, patternUnionTagCheck(union, *pattern, recv))
	}
	for _, variant := range union.Variants {
		checks = append(checks, literalUnionChecks(union, variant, paths, recv)...)
	}
	if pattern := union.PatternVariant; pattern != nil {
		checks = append(checks, patternUnionChecks(union, *pattern, paths, recv)...)
	}
	return checks
}

func patternUnionTagCheck(union dispatch.UnionSpec, pattern dispatch.PatternVariantSpec, recv string) string {
	field, ok := contractshape.LookupField(union.GoType, union.Discriminator)
	if !ok {
		panic(fmt.Sprintf("contractgen: %s has no discriminator %q", union.GoType.Name(), union.Discriminator))
	}
	tags := make([]string, 0, len(union.Variants))
	for _, variant := range union.Variants {
		tags = append(tags, variant.Tag)
	}
	return fmt.Sprintf(
		"unionTag(%q, string(%s.%s), %s, %q)",
		union.Discriminator, recv, field.GoName, valueList(tags), pattern.TagPattern,
	)
}

func literalUnionChecks(
	union dispatch.UnionSpec,
	variant dispatch.VariantSpec,
	paths []string,
	recv string,
) []string {
	applies := fmt.Sprintf("wireFieldEquals(%s, %q, %q)", recv, union.Discriminator, variant.Tag)
	checks := unionBranchChecks(applies, variant.Required, variant.Optional, paths, recv)
	return append(checks, allowedValueChecks(applies, variant.AllowedValues, recv)...)
}

func patternUnionChecks(
	union dispatch.UnionSpec,
	pattern dispatch.PatternVariantSpec,
	paths []string,
	recv string,
) []string {
	applies := fmt.Sprintf("wireFieldMatches(%s, %q, %q)", recv, union.Discriminator, pattern.TagPattern)
	return unionBranchChecks(applies, pattern.Required, pattern.Optional, paths, recv)
}

func unionBranchChecks(applies string, required, optional, paths []string, recv string) []string {
	allowed := append(slices.Clone(required), optional...)
	checks := make([]string, 0, len(required)+len(paths))
	for _, field := range required {
		checks = append(checks, fmt.Sprintf("requiredWhen(%s, %q, %s)", applies, field, recv))
	}
	for _, field := range paths {
		if slices.Contains(allowed, field) {
			continue
		}
		checks = append(checks, fmt.Sprintf("forbiddenWhen(%s, %q, %s)", applies, field, recv))
	}
	return checks
}

func unionPaths(union dispatch.UnionSpec) []string {
	var paths []string
	for _, variant := range union.Variants {
		for _, field := range append(slices.Clone(variant.Required), variant.Optional...) {
			if field != union.Discriminator && !slices.Contains(paths, field) {
				paths = append(paths, field)
			}
		}
	}
	if pattern := union.PatternVariant; pattern != nil {
		for _, field := range append(slices.Clone(pattern.Required), pattern.Optional...) {
			if field != union.Discriminator && !slices.Contains(paths, field) {
				paths = append(paths, field)
			}
		}
	}
	return paths
}

func objectChecks(rules []dispatch.ConditionalRule, recv string) []string {
	var checks []string
	for _, rule := range rules {
		applies := conditionExpression(rule.When, recv)
		for _, field := range rule.Required {
			checks = append(checks, fmt.Sprintf("requiredWhen(%s, %q, %s)", applies, field, recv))
		}
		if len(rule.RequiredAny) > 0 {
			checks = append(checks, fmt.Sprintf(
				"requiredAnyWhen(%s, %s, %s)",
				applies,
				valueList(rule.RequiredAny),
				recv,
			))
		}
		for _, field := range rule.Forbidden {
			checks = append(checks, fmt.Sprintf("forbiddenWhen(%s, %q, %s)", applies, field, recv))
		}
		checks = append(checks, allowedValueChecks(applies, rule.AllowedValues, recv)...)
	}
	return checks
}

func allowedValueChecks(applies string, sets []dispatch.AllowedValueSet, recv string) []string {
	checks := make([]string, 0, len(sets))
	for _, set := range sets {
		checks = append(checks, fmt.Sprintf(
			"allowedValuesWhen(%s, %q, %s, %s)",
			applies,
			set.Field,
			recv,
			valueList(set.Values),
		))
	}
	return checks
}

func conditionExpression(conditions []delivery.FieldCondition, recv string) string {
	if len(conditions) == 0 {
		return "true"
	}
	parts := make([]string, 0, len(conditions))
	for _, condition := range conditions {
		switch condition.Operator.String() {
		case "equals":
			parts = append(parts, fmt.Sprintf(
				"wireFieldEquals(%s, %q, %q)", recv, condition.Field, condition.Value,
			))
		case "present":
			parts = append(parts, fmt.Sprintf("wireFieldPresent(%s, %q)", recv, condition.Field))
		default:
			panic(fmt.Sprintf("contractgen: unsupported conditional operator %q", condition.Operator))
		}
	}
	return strings.Join(parts, " && ")
}

// stringExpr reads a field as a string. A named string type — a closed enum, an id —
// needs the conversion, and a plain string must not have one: an identity conversion
// is what the linter deletes, so emitting one everywhere would make the generated
// file fail the check it is generated to pass.
func stringExpr(shape reflect.Type, selector string, leaf reflect.Type) string {
	const builtinStringTypeName = "string"

	ref := receiverName(shape) + "." + selector
	if leaf.Kind() == reflect.Pointer {
		return ref
	}
	if leaf.Kind() == reflect.String && leaf.Name() != builtinStringTypeName {
		return fmt.Sprintf("string(%s)", ref)
	}
	return ref
}

func valueList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// valueConstraintsFor returns the declared constraints on one field of a shape,
// so the schema walk can state the same rule with its corresponding keyword.
func (s *schemaSet) valueConstraintsFor(owner reflect.Type, field string) []dispatch.FieldConstraint {
	var out []dispatch.FieldConstraint
	owners := append([]reflect.Type{owner}, contractshape.Embeds(owner)...)
	for _, candidate := range owners {
		for _, constraint := range s.values[candidate] {
			if constraint.Field == field && !slices.Contains(out, constraint) {
				out = append(out, constraint)
			}
		}
	}
	return out
}
